[package]
name = "dirt_clump"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Multisphere/clump rigid body composites for non-spherical DEM particles"

[dependencies]
soil_core = { workspace = true, default-features = false }
grass_app.workspace = true
grass_scheduler.workspace = true
soil_derive.workspace = true
dirt_atom.workspace = true
dirt_schedule.workspace = true
serde.workspace = true
toml.workspace = true
rand.workspace = true

[features]
default = []
mpi_backend = ["soil_core/mpi_backend"]
precision-double = ["soil_core/precision-double"]
precision-mixed = ["soil_core/precision-mixed"]
precision-single = ["soil_core/precision-single"]

[dev-dependencies]
dirt_test_utils.workspace = true
