#!/usr/bin/env python3
"""Independent observer for the column-collapse raw-witness campaign.

This program deliberately does not import ``sweep.py``.  It re-reads the raw
release, final-deposit, and arrest records and performs a separate, bin-free
toe measurement before fitting the externally specified planar Lajeunesse law.
It is a second analysis, not a replacement for the benchmark driver's own
provenance checks.  A PASS therefore requires both analyses to pass; a missing
or inconsistent witness is a FAIL, never a synthesized result.

AI-assisted implementation (2026-07-19).  The acceptance target and +/-0.25
band are the existing experimental contract, not generated by this program.
"""

import csv
import math
import os
import sys


HERE = os.path.dirname(os.path.abspath(__file__))
SWEEP = os.path.join(HERE, "sweep")

# Independently stated physical/acceptance contract.  Keep these constants in
# this observer rather than importing the driver so a later driver edit cannot
# silently change both analyses together.
L0 = 0.096
DIAMETER = 0.003
# The support is a frozen bead bed, not a horizontal z cut.  Its top beads and
# mobile grains overlap in z, so classifying the final deposit by height would
# silently turn the 0.60 m long support into a runout.  The release witness
# supplies the actual frozen coordinates for each case; the observer identifies
# those same immutable particles again in the final witness.
BASE_TOP = 0.00375
FROZEN_COORDINATE_TOLERANCE = 1.0e-9
ASPECTS = (0.5, 0.75, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0)
SEEDS = (0, 1, 2)
GRAVITY = 9.81
FROUDE_LIMIT = 0.05
ARREST_INTERVAL = 25_000
ARREST_SAMPLES = 4
LINEAR_TARGET = 1.0
POWER_TARGET = 2.0 / 3.0
TOLERANCE = 0.25


def tag(aspect):
    return f"a{aspect:g}".replace(".", "p")


def case_dir(aspect, seed):
    name = tag(aspect) if seed == 0 else f"{tag(aspect)}_s{seed}"
    return os.path.join(SWEEP, name, "data")


def particles(path):
    with open(path, newline="") as source:
        rows = list(csv.DictReader(source))
    if not rows or set(rows[0]) != {"x", "y", "z", "radius"}:
        raise ValueError("expected nonempty x,y,z,radius CSV")
    answer = []
    for row in rows:
        try:
            p = tuple(float(row[k]) for k in ("x", "y", "z", "radius"))
        except (KeyError, ValueError) as exc:
            raise ValueError("non-numeric particle row") from exc
        if not all(math.isfinite(v) for v in p) or p[3] <= 0.0:
            raise ValueError("non-finite particle geometry")
        answer.append(p)
    return answer


def terminal(path, expected):
    with open(path, newline="") as source:
        rows = list(csv.DictReader(source))
    if len(rows) != 1 or set(rows[0]) != {"particle_count", "max_speed_m_s"}:
        raise ValueError("expected one terminal state")
    try:
        count, speed = int(rows[0]["particle_count"]), float(rows[0]["max_speed_m_s"])
    except (KeyError, ValueError) as exc:
        raise ValueError("invalid terminal state") from exc
    if count != expected or not math.isfinite(speed) or speed < 0.0:
        raise ValueError("terminal population or speed is invalid")
    return speed


def arrested(path):
    with open(path, newline="") as source:
        rows = list(csv.DictReader(source))
    if len(rows) < ARREST_SAMPLES:
        raise ValueError("too few arrest samples")
    window = rows[-ARREST_SAMPLES:]
    try:
        steps = [int(row["collapse_step"]) for row in window]
        speeds = [float(row["max_speed_m_s"]) for row in window]
    except (KeyError, ValueError) as exc:
        raise ValueError("invalid arrest record") from exc
    if any(b - a != ARREST_INTERVAL for a, b in zip(steps, steps[1:])):
        raise ValueError("arrest samples are not evenly spaced")
    if any(not math.isfinite(v) or v < 0.0 for v in speeds):
        raise ValueError("invalid arrest speed")
    if max(speeds) / math.sqrt(GRAVITY * DIAMETER) > FROUDE_LIMIT:
        raise ValueError("terminal arrest window exceeds Froude limit")


def coordinate_key(particle):
    """A stable key for a frozen witness coordinate.

    Recorder CSVs are text serializations, so round only enough to tolerate
    serialization noise, not enough to confuse two physical grains.
    """
    return tuple(round(value / FROZEN_COORDINATE_TOLERANCE)
                 for value in particle)


def split_frozen_support(release, deposit):
    """Return mobile release/final particles after exact support matching.

    A rough base cannot be removed by a final-state z threshold: its upper
    spheres occupy the same height range as grains in the toe.  Instead, use
    the pre-release record to identify the frozen support and require every
    such coordinate to remain present in the final frame.  This is a physical
    boundary check as well as an exclusion rule; a moving or missing support
    invalidates the observation.
    """
    frozen = [p for p in release if p[2] <= BASE_TOP]
    active = [p for p in release if p[2] > BASE_TOP]
    if not frozen or not active:
        raise ValueError("release does not separate frozen support and active grains")
    frozen_keys = {coordinate_key(p) for p in frozen}
    if len(frozen_keys) != len(frozen):
        raise ValueError("duplicate frozen-support coordinates")
    final_keys = [coordinate_key(p) for p in deposit]
    if not frozen_keys.issubset(final_keys):
        raise ValueError("frozen support moved or is missing from final witness")
    mobile_final = [p for p, key in zip(deposit, final_keys) if key not in frozen_keys]
    if len(mobile_final) != len(active):
        raise ValueError("mobile population changed after support exclusion")
    return active, mobile_final


def release_aspect(active):
    if not active:
        raise ValueError("release has no grains above frozen base")
    width = max(x + r for x, _, r in active) - min(x - r for x, _, r in active)
    if width < 0.95 * L0:
        raise ValueError("release does not span the controlled column width")
    height = max(z + r for _, z, r in active) - DIAMETER
    if height <= 0.0 or not math.isfinite(height):
        raise ValueError("invalid release height")
    return height / L0


def interval_toe(deposit):
    """Continuous silhouette toe for the mobile deposit.

    Eligible mobile particles are at least one diameter above the containment
    plane.  Their radius-expanded x intervals are unioned continuously, then
    the deposit component that overlaps the original [0, L0] column footprint
    is followed to its downstream edge.  A physical gap greater than one
    diameter separates components.  This avoids the driver's occupancy grid
    and, unlike a leftmost-interval walk, cannot let an isolated rear grain
    select the toe.
    """
    intervals = []
    for x, _, z, radius in deposit:
        if z >= DIAMETER:
            intervals.append((x - radius, x + radius))
    if not intervals:
        raise ValueError("deposit has no two-layer toe particles")
    intervals.sort()
    components = []
    left, right = intervals[0]
    for start, end in intervals[1:]:
        if start - right > DIAMETER:
            components.append((left, right))
            left, right = start, end
        else:
            right = max(right, end)
    components.append((left, right))
    anchored = [(left, right) for left, right in components
                if left <= L0 and right >= 0.0]
    if len(anchored) != 1:
        raise ValueError("deposit has no unique component anchored to release footprint")
    return max(L0, anchored[0][1])


def slope(points):
    if len(points) < 2 or any(x <= 0.0 or y <= 0.0 for x, y in points):
        raise ValueError("cannot fit non-positive or insufficient points")
    xs = [math.log(x) for x, _ in points]
    ys = [math.log(y) for _, y in points]
    mean_x, mean_y = sum(xs) / len(xs), sum(ys) / len(ys)
    denominator = sum((x - mean_x) ** 2 for x in xs)
    if denominator == 0.0:
        raise ValueError("degenerate aspect values")
    return sum((x - mean_x) * (y - mean_y) for x, y in zip(xs, ys)) / denominator


def observe_case(aspect, seed):
    directory = case_dir(aspect, seed)
    paths = {
        name: os.path.join(directory, filename)
        for name, filename in (
            ("release", "column_collapse_release.csv"),
            ("deposit", "column_collapse_results.csv"),
            ("terminal", "column_collapse_final_state.csv"),
            ("arrest", "column_collapse_arrest.csv"),
        )
    }
    absent = [name for name, path in paths.items() if not os.path.isfile(path)]
    if absent:
        raise ValueError("missing " + ", ".join(absent) + " witness")
    release, deposit = particles(paths["release"]), particles(paths["deposit"])
    if len(release) != len(deposit):
        raise ValueError("release/final population changed")
    terminal(paths["terminal"], len(release))
    arrested(paths["arrest"])
    active, mobile_deposit = split_frozen_support(release, deposit)
    return release_aspect(active), (interval_toe(mobile_deposit) - L0) / L0


def main():
    rows, errors = [], []
    for aspect in ASPECTS:
        observed = []
        for seed in SEEDS:
            try:
                observed.append(observe_case(aspect, seed))
            except (OSError, csv.Error, ValueError) as exc:
                errors.append(f"a={aspect:g}, seed={seed}: {exc}")
        if len(observed) == len(SEEDS):
            rows.append((sum(a for a, _ in observed) / len(observed),
                         sum(r for _, r in observed) / len(observed)))
    if errors or len(rows) != len(ASPECTS):
        print("INDEPENDENT OBSERVER: INCOMPLETE/FAIL")
        for error in errors:
            print("  " + error)
        return 1
    low = [(a, r) for a, r in rows if a <= 3.0]
    high = [(a, r) for a, r in rows if a >= 3.0]
    try:
        linear, power = slope(low), slope(high)
    except ValueError as exc:
        print(f"INDEPENDENT OBSERVER: FAIL ({exc})")
        return 1
    linear_ok = abs(linear - LINEAR_TARGET) <= TOLERANCE
    power_ok = abs(power - POWER_TARGET) <= TOLERANCE
    print("INDEPENDENT OBSERVER (bin-free toe, raw witnesses only)")
    print(f"  planar Lajeunesse target: linear {LINEAR_TARGET:.3f}, power {POWER_TARGET:.3f}; band +/-{TOLERANCE:.2f}")
    print(f"  fitted exponents: linear {linear:.3f} ({'PASS' if linear_ok else 'FAIL'}), power {power:.3f} ({'PASS' if power_ok else 'FAIL'})")
    return 0 if linear_ok and power_ok else 1


if __name__ == "__main__":
    sys.exit(main())
