#!/bin/bash
# Submit every benchmark job to PBS. Run after `generate`,
# then `scaling_gas.py graph` once they finish.
cd "$(dirname "$0")"
(cd "runs/dirt_strong_dense_c1" && qsub pbs_submit)
(cd "runs/lammps_strong_dense_c1" && qsub pbs_submit)
(cd "runs/dirt_strong_dense_c2" && qsub pbs_submit)
(cd "runs/lammps_strong_dense_c2" && qsub pbs_submit)
(cd "runs/dirt_strong_dense_c4" && qsub pbs_submit)
(cd "runs/lammps_strong_dense_c4" && qsub pbs_submit)
(cd "runs/dirt_strong_dense_c8" && qsub pbs_submit)
(cd "runs/lammps_strong_dense_c8" && qsub pbs_submit)
(cd "runs/dirt_strong_dense_c16" && qsub pbs_submit)
(cd "runs/lammps_strong_dense_c16" && qsub pbs_submit)
(cd "runs/dirt_strong_dilute_c1" && qsub pbs_submit)
(cd "runs/lammps_strong_dilute_c1" && qsub pbs_submit)
(cd "runs/dirt_strong_dilute_c2" && qsub pbs_submit)
(cd "runs/lammps_strong_dilute_c2" && qsub pbs_submit)
(cd "runs/dirt_strong_dilute_c4" && qsub pbs_submit)
(cd "runs/lammps_strong_dilute_c4" && qsub pbs_submit)
(cd "runs/dirt_strong_dilute_c8" && qsub pbs_submit)
(cd "runs/lammps_strong_dilute_c8" && qsub pbs_submit)
(cd "runs/dirt_strong_dilute_c16" && qsub pbs_submit)
(cd "runs/lammps_strong_dilute_c16" && qsub pbs_submit)
(cd "runs/dirt_weak_dense_c1" && qsub pbs_submit)
(cd "runs/lammps_weak_dense_c1" && qsub pbs_submit)
(cd "runs/dirt_weak_dense_c2" && qsub pbs_submit)
(cd "runs/lammps_weak_dense_c2" && qsub pbs_submit)
(cd "runs/dirt_weak_dense_c4" && qsub pbs_submit)
(cd "runs/lammps_weak_dense_c4" && qsub pbs_submit)
(cd "runs/dirt_weak_dense_c8" && qsub pbs_submit)
(cd "runs/lammps_weak_dense_c8" && qsub pbs_submit)
(cd "runs/dirt_weak_dense_c16" && qsub pbs_submit)
(cd "runs/lammps_weak_dense_c16" && qsub pbs_submit)
(cd "runs/dirt_weak_dilute_c1" && qsub pbs_submit)
(cd "runs/lammps_weak_dilute_c1" && qsub pbs_submit)
(cd "runs/dirt_weak_dilute_c2" && qsub pbs_submit)
(cd "runs/lammps_weak_dilute_c2" && qsub pbs_submit)
(cd "runs/dirt_weak_dilute_c4" && qsub pbs_submit)
(cd "runs/lammps_weak_dilute_c4" && qsub pbs_submit)
(cd "runs/dirt_weak_dilute_c8" && qsub pbs_submit)
(cd "runs/lammps_weak_dilute_c8" && qsub pbs_submit)
(cd "runs/dirt_weak_dilute_c16" && qsub pbs_submit)
(cd "runs/lammps_weak_dilute_c16" && qsub pbs_submit)
