#!/usr/bin/env python3
"""
Rod-like glued-sphere Lees-Edwards shear benchmark after Guo et al. (JFM 713, 2012).

The harness keeps the simulation small enough for regression, but it preserves the
published comparison that matters for DIRT's rod/clump path: frictionless glued
spheres at fixed equivalent-volume diameter, sheared with Lees-Edwards boundaries.
It gates two dimensionless aspect-ratio trends reported by Guo/Wassgren/
Ketterhagen/Hancock/Curtis for elongated glued-sphere particles in the dilute
regime:

  * dilute Bagnold-normalized pressure p/(rho d_v^2 gamma_dot^2) decreases with AR;
  * dilute Bagnold-normalized shear stress |sigma_xy|/(rho d_v^2 gamma_dot^2)
    decreases with AR.

It also plots apparent friction |sigma_xy|/p against the paper's digitized Fig. 18
trend for glued-sphere rods, and the measured long-axis flow alignment for context.
"""

import csv
import math
import os
import subprocess
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))
EXAMPLE = "bench_rod_shear_aspect_ratio"
DATA_DIR = os.path.join(SCRIPT_DIR, "data")
SWEEP_DIR = os.path.join(SCRIPT_DIR, "sweep")
PLOT_DIR = os.path.join(SCRIPT_DIR, "plots")

L = 0.008
PHI = 0.010
D_EQ = 8.0e-4
DENSITY = 2500.0
YOUNGS_MOD = 8.7e7
POISSON = 0.30
RESTITUTION = 0.90
FRICTION = 0.0
GDOT = 100.0
DT = 2.0e-7
SETTLE_STEPS = 2000
SHEAR_STEPS = 30000
THERMO = 1000
ASPECT_RATIOS = [1, 2, 4, 6]

V_BODY = math.pi / 6.0 * D_EQ ** 3
COUNT = max(12, round(PHI * L ** 3 / V_BODY))

FIG18_DIGITIZED = os.path.join(DATA_DIR, "guo2012_fig18_glued_mu_digitized.csv")

CONFIG_TEMPLATE = """\
# Auto-generated by sweep.py. Frictionless glued-sphere rod shear, case {case}.
[comm]
processors_x = 1
processors_y = 1
processors_z = 1

[domain]
x_low = 0.0
x_high = {L}
y_low = 0.0
y_high = {L}
z_low = 0.0
z_high = {L}
boundary_x = "periodic"
boundary_y = "periodic"
boundary_z = "periodic"

[neighbor]
skin_fraction = 1.2
bin_size = {bin_size}
every = 1

[dem]
contact_model = "hertz"

[[dem.materials]]
name = "glass"
youngs_mod = {E}
poisson_ratio = {nu}
restitution = {e}
friction = {mu_p}

[[clump.definitions]]
name = "rod_ar{ar}"
spheres = [
{sphere_lines}
]

[[clump.insert]]
definition = "rod_ar{ar}"
count = {count}
density = {density}
material = "glass"
velocity = 0.04
random_orientation = true
seed = {seed}
region = {{ type = "block", min = [{pad}, {pad}, {pad}], max = [{hi}, {hi}, {hi}] }}

[output]
dir = "{out_dir}"

[[run]]
name = "settle"
steps = {settle}
thermo = {thermo}
dt = {dt}

[[run]]
name = "shear"
steps = {shear}
thermo = {thermo}
dt = {dt}
deform = {{ xy = {{ style = "erate", rate = {gdot} }} }}
"""


def rod_spheres(ar):
    d_sub = D_EQ / (ar ** (1.0 / 3.0))
    r = 0.5 * d_sub
    start = -0.5 * (ar - 1) * d_sub
    lines = []
    for i in range(ar):
        x = start + i * d_sub
        lines.append(f'    {{ offset = [{x:.10e}, 0.0, 0.0], radius = {r:.10e} }},')
    return "\n".join(lines), r, 0.5 * ar * d_sub


def case_name(ar):
    return f"ar{ar}"


def generate():
    os.makedirs(SWEEP_DIR, exist_ok=True)
    for ar in ASPECT_RATIOS:
        case = case_name(ar)
        cdir = os.path.join(SWEEP_DIR, case)
        os.makedirs(cdir, exist_ok=True)
        sphere_lines, r_sub, half_len = rod_spheres(ar)
        pad = half_len * 1.05
        cfg = CONFIG_TEMPLATE.format(
            case=case,
            L=L,
            bin_size=max(2.4 * r_sub, 1.2 * D_EQ),
            E=YOUNGS_MOD,
            nu=POISSON,
            e=RESTITUTION,
            mu_p=FRICTION,
            ar=ar,
            sphere_lines=sphere_lines,
            count=COUNT,
            density=DENSITY,
            seed=1000 + ar,
            pad=pad,
            hi=L - pad,
            out_dir=os.path.join(DATA_DIR, case),
            settle=SETTLE_STEPS,
            shear=SHEAR_STEPS,
            thermo=THERMO,
            dt=DT,
            gdot=GDOT,
        )
        with open(os.path.join(cdir, "config.toml"), "w") as f:
            f.write(cfg)
    print(f"generated {len(ASPECT_RATIOS)} cases with {COUNT} rods each")


def build():
    subprocess.run(
        [
            "cargo",
            "build",
            "--release",
            "--no-default-features",
            "--features",
            "precision-double",
            "--example",
            EXAMPLE,
        ],
        cwd=REPO_ROOT,
        check=True,
    )


def start():
    if not os.path.isdir(SWEEP_DIR):
        generate()
    build()
    exe = os.path.join(REPO_ROOT, "target", "release", "examples", EXAMPLE)
    for ar in ASPECT_RATIOS:
        case = case_name(ar)
        csv_path = os.path.join(DATA_DIR, case, "rod_shear_results.csv")
        if os.path.exists(csv_path):
            os.remove(csv_path)
        cfg = os.path.join(SWEEP_DIR, case, "config.toml")
        log = os.path.join(SWEEP_DIR, case, "run.log")
        print(f"running AR={ar} ...", flush=True)
        with open(log, "w") as lf:
            subprocess.run([exe, cfg], cwd=REPO_ROOT, stdout=lf, stderr=subprocess.STDOUT, check=True)


def steady_average(path, frac=0.50):
    rows = [r for r in csv.DictReader(open(path)) if float(r["gdot"]) > 0.0]
    rows = rows[int(len(rows) * frac):]
    if not rows:
        return None
    out = {}
    for key in ["gdot", "p", "sxy", "syy", "mu", "T", "phi", "order_x", "align_x"]:
        out[key] = sum(float(r[key]) for r in rows) / len(rows)
    return out


def collect():
    pts = []
    for ar in ASPECT_RATIOS:
        path = os.path.join(DATA_DIR, case_name(ar), "rod_shear_results.csv")
        if not os.path.isfile(path):
            print(f"missing {path}")
            continue
        s = steady_average(path)
        if s is None:
            continue
        bagnold = DENSITY * D_EQ ** 2 * GDOT ** 2
        pts.append(
            {
                "ar": ar,
                "p_star": s["p"] / bagnold,
                "sxy_star": abs(s["sxy"]) / bagnold,
                "mu": abs(s["sxy"]) / abs(s["p"]) if s["p"] else float("nan"),
                **s,
            }
        )
    return sorted(pts, key=lambda p: p["ar"])


def load_fig18_digitized():
    rows = list(csv.DictReader(open(FIG18_DIGITIZED)))
    return {
        int(float(r["aspect_ratio"])): float(r["apparent_friction"])
        for r in rows
        if abs(float(r["solid_fraction"]) - 0.05) < 1.0e-9
    }


def monotone_decreasing(vals):
    return all(a > b for a, b in zip(vals, vals[1:]))


def monotone_increasing(vals):
    return all(a < b for a, b in zip(vals, vals[1:]))


def graph():
    pts = collect()
    if len(pts) != len(ASPECT_RATIOS):
        print("FAIL: missing case data")
        return 1

    ar = [p["ar"] for p in pts]
    pstar = [p["p_star"] for p in pts]
    align = [p["align_x"] for p in pts]
    mu = [p["mu"] for p in pts]
    phi = [p["phi"] for p in pts]

    elongated = [p for p in pts if p["ar"] >= 2]
    pressure_pass = monotone_decreasing([p["p_star"] for p in elongated])
    shear_pass = monotone_decreasing([p["sxy_star"] for p in elongated])
    phi_pass = all(0.006 <= x <= 0.014 for x in phi)

    print("=== Guo et al. rod shear aspect-ratio trends ===")
    print("AR   phi      p*        |sxy|*    mu       align_x")
    for p in pts:
        print(
            f"{p['ar']:2d}  {p['phi']:.4f}  {p['p_star']:.4e}  {p['sxy_star']:.4e}  "
            f"{p['mu']:.4f}  {p['align_x']:.4f}"
        )
    print(f"elongated-rod pressure p/(rho d_v^2 gdot^2) decreases with AR: {'PASS' if pressure_pass else 'FAIL'}")
    print(f"elongated-rod shear |sxy|/(rho d_v^2 gdot^2) decreases with AR: {'PASS' if shear_pass else 'FAIL'}")
    print(f"realized dilute solid fraction stays near target: {'PASS' if phi_pass else 'FAIL'}")

    os.makedirs(PLOT_DIR, exist_ok=True)
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib unavailable; plot skipped")
        return 0 if pressure_pass and shear_pass and phi_pass else 1

    fig, (ax0, ax1, ax2) = plt.subplots(1, 3, figsize=(13, 4.0))
    sstar = [p["sxy_star"] for p in pts]
    ax0.plot(ar, pstar, "o-", color="tab:blue", label="DIRT pressure")
    ax0.plot(ar, sstar, "s-", color="tab:purple", label="DIRT shear")
    ax0.axvspan(1.5, max(ar) + 0.2, color="tab:blue", alpha=0.06, label="elongated-rod gate")
    ax0.annotate("Guo et al.: dilute elongated-rod stresses decrease as AR increases", xy=(4.0, pstar[2]),
                 xytext=(1.1, max(pstar) * 0.92), fontsize=8,
                 arrowprops=dict(arrowstyle="->", color="0.35", lw=0.8))
    ax0.set_xlabel("aspect ratio AR")
    ax0.set_ylabel(r"$\sigma^*/(\rho d_v^2\dot\gamma^2)$")
    ax0.set_title("Dilute pressure and shear")
    ax0.grid(True, alpha=0.3)
    ax0.legend(fontsize=7)

    ax1.plot(ar, align, "o-", color="tab:green", label="DIRT <|u_x|>")
    ax1.set_xlabel("aspect ratio AR")
    ax1.set_ylabel(r"flow alignment $\langle |u_x| \rangle$")
    ax1.set_title("Long-axis alignment")
    ax1.grid(True, alpha=0.3)

    fig18 = load_fig18_digitized()
    ref_ar = sorted(fig18)
    ax2.plot(ref_ar, [fig18[a] for a in ref_ar], "s--", color="0.25",
             label="Guo Fig. 18 digitized, glued spheres, nu~0.05")
    ax2.plot(ar, mu, "o-", color="tab:red", label="DIRT")
    ax2.set_xlabel("aspect ratio AR")
    ax2.set_ylabel(r"$|\sigma_{xy}|/p$")
    ax2.set_title("Apparent friction")
    ax2.grid(True, alpha=0.3)
    ax2.legend(fontsize=7)

    fig.suptitle(
        "Rod-like shear-flow aspect-ratio benchmark: "
        f"pressure {'PASS' if pressure_pass else 'FAIL'}, shear {'PASS' if shear_pass else 'FAIL'}",
        fontsize=11,
    )
    fig.tight_layout()
    fig.savefig(os.path.join(PLOT_DIR, "rod_shear_aspect_ratio.png"), dpi=140)
    plt.close(fig)

    return 0 if pressure_pass and shear_pass and phi_pass else 1


def main():
    cmd = sys.argv[1] if len(sys.argv) > 1 else "smoke"
    if cmd in ("generate", "gen"):
        generate()
    elif cmd == "start":
        start()
    elif cmd == "graph":
        raise SystemExit(graph())
    elif cmd in ("smoke", "full"):
        generate()
        start()
        raise SystemExit(graph())
    else:
        print("usage: sweep.py [smoke|full|generate|start|graph]")
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
