#!/usr/bin/env python3
"""
Beverloo hopper-discharge benchmark driver.

Discharges a quasi-2D slot hopper through a bottom slot of opening width D over a
sweep of D values, fits the steady mass-flow rate W from the cumulative-discharge
curve, and checks that W follows Beverloo's law for a 2D slot,

    W = C · ρ_b · √g · (D − k·d)^(3/2)   (per unit slot depth),

i.e. on a log–log plot of W vs (D − k·d) the slope (exponent) is 3/2 and W → 0 as
D → k·d. The fit recovers BOTH the exponent and the Beverloo length k·d.

Commands (from anywhere):
    python3 examples/bench_hopper_beverloo/sweep.py generate   # write per-case configs
    python3 examples/bench_hopper_beverloo/sweep.py start      # build + run all sims -> CSV
    python3 examples/bench_hopper_beverloo/sweep.py graph      # validate + plot
    python3 examples/bench_hopper_beverloo/sweep.py            # all three, in order

LAMMPS is not used here (a templated multi-stage hopper with a runtime-removed
blocker is not a drop-in LAMMPS input); validation is against Beverloo theory.

Outputs:
    sweep/<case>/config.toml       DIRT configs                       (gitignored)
    data/sweep.csv                 per-D fitted W                     (gitignored)
    data/curve_D<...>.csv          per-D cumulative-discharge curves  (gitignored)
    plots/*.png                    final figures                      (tracked)

Reference:
    W. A. Beverloo, H. A. Leniger, J. van de Velde, "The flow of granular solids
    through orifices", Chem. Eng. Sci. 15 (1961) 260-269.
    For a long slot of width D the per-unit-length flow scales as (D - k d)^(3/2).
"""

import os
import sys
import csv
import math
import shutil
import subprocess

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))
EXAMPLE = "bench_hopper_beverloo"

SWEEP_DIR = os.path.join(SCRIPT_DIR, "sweep")
DATA_DIR = os.path.join(SCRIPT_DIR, "data")
PLOT_DIR = os.path.join(SCRIPT_DIR, "plots")
SWEEP_CSV = os.path.join(DATA_DIR, "sweep.csv")   # fitted W vs D

# LAMMPS is intentionally unused for this multi-stage hopper benchmark.
LAMMPS_BINS = []

# ── Geometry (fixed across the sweep; only D changes) ─────────────────────────
X_CENTER = 0.08      # slot center x [m]
X_BIN_LO = 0.02      # left bin wall x
X_BIN_HI = 0.14      # right bin wall x
Z_FUNNEL_TOP = 0.18  # top of the wedge funnel
Z_ORIFICE = 0.05     # slot plane (blocker height)
Z_TOP = 0.40         # ceiling
Y_DEPTH = 0.012      # periodic slot depth [m]
ORIFICE_Z_COUNT = 0.045  # discharge-counting plane (just below the slot)

# ── Material / particle properties ────────────────────────────────────────────
D_GRAIN = 0.004      # particle diameter d [m]
RADIUS = D_GRAIN / 2
DENSITY = 2500.0     # kg/m^3
YOUNGS = 5.0e7       # Pa (softened: rigid-grain Beverloo regime, larger stable dt)
POISSON = 0.3
RESTITUTION = 0.5
FRICTION = 0.5
GZ = -9.81           # m/s^2
G = abs(GZ)

# Beverloo constants (theory targets; C is order-1, validate the exponent & k).
K_BEVERLOO = 1.4
EXPONENT_2D = 1.5    # slot (per unit width)

# ── Sweep over slot opening D [m] (all > a few grain diameters) ──────────────
# k·d = 1.4·0.004 = 0.0056 m, so the smallest D≈0.016 gives (D-kd)≈0.0104 (>2.5 d).
D_LIST = [0.016, 0.020, 0.024, 0.028, 0.032]

N_PARTICLES = 1400
DT = 2.0e-5
FILL_STEPS = 60000     # 1.2 s settle
FLOW_STEPS = 90000     # 1.8 s discharge (smallest D drains slowest)
SAMPLE_INTERVAL = 2000

# ── DIRT config template ──────────────────────────────────────────────────────
TOML_TEMPLATE = """# Auto-generated by sweep.py — D = {D:.4f} m
[comm]
processors_x = 1
processors_y = 1
processors_z = 1
[domain]
x_low = 0.0
x_high = 0.16
y_low = 0.0
y_high = {ydepth}
z_low = 0.0
z_high = {ztop}
boundary_x = "fixed"
boundary_y = "periodic"
boundary_z = "fixed"
[neighbor]
skin_fraction = 1.2
bin_size = {binsize}
[gravity]
gz = {gz}
[[dem.materials]]
name = "glass"
youngs_mod = {youngs:.6e}
poisson_ratio = {poisson}
restitution = {restitution}
friction = {friction}
[[particles.insert]]
material = "glass"
count = {count}
radius = {radius}
density = {density}
velocity_z = -0.2
region = {{ type = "block", min = [0.025, 0.0, 0.20], max = [0.135, {ydepth}, 0.38] }}
[[wall]]
point_x = {xbinlo}
point_z = 0.0
normal_x = 1.0
material = "glass"
[[wall]]
point_x = {xbinhi}
point_z = 0.0
normal_x = -1.0
material = "glass"
[[wall]]
point_z = {ztop}
normal_z = -1.0
material = "glass"
[[wall]]
point_x = {xbinlo}
point_z = {zfunneltop}
normal_x = 0.13
normal_z = {fn_z:.6f}
material = "glass"
bound_z_low = {zorifice_m}
bound_z_high = {zfunneltop_p}
[[wall]]
point_x = {xbinhi}
point_z = {zfunneltop}
normal_x = -0.13
normal_z = {fn_z:.6f}
material = "glass"
bound_z_low = {zorifice_m}
bound_z_high = {zfunneltop_p}
[[wall]]
point_z = {zorifice}
normal_z = 1.0
material = "glass"
name = "blocker"
bound_z_low = 0.0
bound_z_high = {zorifice_p}
[hopper_beverloo]
orifice_z = {orifice_z_count}
sample_interval = {sample}
[output]
dir = "{outdir}"
[[run]]
name = "filling"
steps = {fill_steps}
thermo = 10000
dt = {dt:.6e}
[[run]]
name = "flowing"
steps = {flow_steps}
thermo = 10000
dt = {dt:.6e}
"""


# ── helpers ──────────────────────────────────────────────────────────────────
def case_tag(D):
    return f"D_{D:.4f}"


def case_dir(D):
    return os.path.join(SWEEP_DIR, case_tag(D))


def find_lammps():
    for b in LAMMPS_BINS:
        p = shutil.which(b)
        if p:
            return p
    return None


def _dirt_config(D, outdir):
    # Inward funnel normal z-component for the slot opening of width D:
    # left funnel from (X_BIN_LO, Z_FUNNEL_TOP) to (X_CENTER - D/2, Z_ORIFICE).
    fn_z = (X_CENTER - D / 2) - X_BIN_LO   # = 0.06 - D/2
    return TOML_TEMPLATE.format(
        D=D, ydepth=Y_DEPTH, ztop=Z_TOP, binsize=max(0.009, 2.2 * RADIUS),
        gz=GZ, youngs=YOUNGS, poisson=POISSON, restitution=RESTITUTION,
        friction=FRICTION, count=N_PARTICLES, radius=RADIUS, density=DENSITY,
        xbinlo=X_BIN_LO, xbinhi=X_BIN_HI, ztop2=Z_TOP, zfunneltop=Z_FUNNEL_TOP,
        fn_z=fn_z, zorifice=Z_ORIFICE, zorifice_m=Z_ORIFICE - 0.001,
        zorifice_p=Z_ORIFICE + 0.001, zfunneltop_p=Z_FUNNEL_TOP + 0.001,
        orifice_z_count=ORIFICE_Z_COUNT, sample=SAMPLE_INTERVAL, outdir=outdir,
        fill_steps=FILL_STEPS, flow_steps=FLOW_STEPS, dt=DT,
    )


# ── generate ─────────────────────────────────────────────────────────────────
def generate():
    n = 0
    for D in D_LIST:
        cdir = case_dir(D)
        os.makedirs(cdir, exist_ok=True)
        with open(os.path.join(cdir, "config.toml"), "w") as f:
            f.write(_dirt_config(D, cdir))
        n += 1
    print(f"Generated {n} DIRT sweep configs under {SWEEP_DIR}")


# ── start ────────────────────────────────────────────────────────────────────
def _fit_flow_rate(curve):
    """Least-squares slope of cumulative discharged mass vs time over the steady
    middle of the run (10%-90% of the final discharged mass). Returns (W, n_pts)."""
    if len(curve) < 4:
        return None, 0
    m_final = max(m for _, m in curve)
    if m_final <= 0:
        return None, 0
    lo, hi = 0.10 * m_final, 0.90 * m_final
    pts = [(t, m) for t, m in curve if lo <= m <= hi]
    if len(pts) < 3:
        # Fall back to the rising portion (mass strictly increasing).
        pts = [(t, m) for t, m in curve if 0 < m < m_final]
    if len(pts) < 3:
        return None, 0
    n = len(pts)
    sx = sum(t for t, _ in pts)
    sy = sum(m for _, m in pts)
    sxx = sum(t * t for t, _ in pts)
    sxy = sum(t * m for t, m in pts)
    denom = n * sxx - sx * sx
    if abs(denom) < 1e-30:
        return None, 0
    W = (n * sxy - sx * sy) / denom
    return W, n


def _run_dirt(D, cdir):
    """Run one DIRT case; return (W, curve) where curve is [(t, mass), ...]."""
    config = os.path.join(cdir, "config.toml")
    res = os.path.join(cdir, "data", "hopper_beverloo_results.csv")
    if os.path.exists(res):
        os.remove(res)
    log = os.path.join(cdir, "run.log")
    with open(log, "w") as lf:
        proc = subprocess.run(
            ["cargo", "run", "--release", "--example", EXAMPLE,
             "--no-default-features", "--", config],
            cwd=REPO_ROOT, stdout=lf, stderr=subprocess.STDOUT,
        )
    if proc.returncode != 0 or not os.path.isfile(res):
        return None, []
    curve = []
    with open(res) as f:
        for r in csv.DictReader(f):
            curve.append((float(r["time"]), float(r["mass"])))
    W, _ = _fit_flow_rate(curve)
    return W, curve


def _write_curve(D, curve):
    path = os.path.join(DATA_DIR, f"curve_{case_tag(D)}.csv")
    with open(path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["time", "mass"])
        for t, m in curve:
            w.writerow([f"{t:.10e}", f"{m:.10e}"])


def start():
    os.makedirs(DATA_DIR, exist_ok=True)
    # Wipe stale per-case + sweep results so nothing old can be re-plotted.
    for fn in os.listdir(DATA_DIR):
        if fn.startswith("curve_") or fn == os.path.basename(SWEEP_CSV):
            os.remove(os.path.join(DATA_DIR, fn))

    print(f"Building {EXAMPLE} (release)...", flush=True)
    subprocess.run(["cargo", "build", "--release", "--example", EXAMPLE,
                    "--no-default-features"], cwd=REPO_ROOT, check=True)

    if find_lammps():
        print("LAMMPS: present but unused for this hopper benchmark (theory only).")
    else:
        print("LAMMPS: not used for this benchmark — validating against Beverloo.")

    rows = []
    n = len(D_LIST)
    for i, D in enumerate(D_LIST, 1):
        cdir = case_dir(D)
        if not os.path.isfile(os.path.join(cdir, "config.toml")):
            print(f"  [{i}/{n}] missing config for D={D} — run 'generate' first.")
            continue
        print(f"  [{i}/{n}] D={D:.4f} m ...", end="  ", flush=True)
        W, curve = _run_dirt(D, cdir)
        if W is None:
            print("DIRT FAILED")
            continue
        _write_curve(D, curve)
        D_eff = D - K_BEVERLOO * D_GRAIN
        rows.append({"D": D, "D_eff": D_eff, "W": W})
        print(f"W = {W:.4e} kg/s   (D-kd = {D_eff*1e3:.2f} mm)")

    if not rows:
        print("\nERROR: no DIRT results collected.")
        sys.exit(1)
    with open(SWEEP_CSV, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["D", "D_eff", "W"])
        w.writeheader()
        for r in rows:
            w.writerow(r)
    print(f"\n{len(rows)}/{n} cases -> {SWEEP_CSV}")


# ── graph (validate + plot) ──────────────────────────────────────────────────
def _load_sweep():
    if not os.path.isfile(SWEEP_CSV):
        return []
    with open(SWEEP_CSV) as f:
        return [{k: float(v) for k, v in r.items()} for r in csv.DictReader(f)]


def _load_curve(D):
    path = os.path.join(DATA_DIR, f"curve_{case_tag(D)}.csv")
    if not os.path.isfile(path):
        return []
    with open(path) as f:
        return [(float(r["time"]), float(r["mass"])) for r in csv.DictReader(f)]


def _loglog_fit(xs, ys):
    """Fit ln(y) = m·ln(x) + b; return (slope m, intercept b, R^2)."""
    lx = [math.log(x) for x in xs]
    ly = [math.log(y) for y in ys]
    n = len(lx)
    sx, sy = sum(lx), sum(ly)
    sxx = sum(v * v for v in lx)
    sxy = sum(a * b for a, b in zip(lx, ly))
    denom = n * sxx - sx * sx
    m = (n * sxy - sx * sy) / denom
    b = (sy - m * sx) / n
    yhat = [m * x + b for x in lx]
    ybar = sy / n
    ss_res = sum((a - p) ** 2 for a, p in zip(ly, yhat))
    ss_tot = sum((a - ybar) ** 2 for a in ly)
    r2 = 1.0 - ss_res / ss_tot if ss_tot > 0 else 0.0
    return m, b, r2


def validate(rows):
    """Fit the Beverloo exponent on log-log (W vs D-kd) and check it ≈ 3/2."""
    EXP_TOL = 0.25        # |fitted exponent - 1.5| must be within this
    R2_MIN = 0.97         # the power law must fit well
    rows = sorted(rows, key=lambda r: r["D"])
    xs = [r["D_eff"] for r in rows]
    ys = [r["W"] for r in rows]

    print("\n=== Beverloo validation (2D slot, exponent target = 3/2) ===")
    print(f"  k = {K_BEVERLOO},  d = {D_GRAIN*1e3:.1f} mm,  k·d = {K_BEVERLOO*D_GRAIN*1e3:.2f} mm")
    print(f"  {'D (mm)':>8}{'D-kd (mm)':>12}{'W (kg/s)':>14}")
    for r in rows:
        print(f"  {r['D']*1e3:>8.1f}{r['D_eff']*1e3:>12.2f}{r['W']:>14.4e}")

    if any(x <= 0 for x in xs) or any(y <= 0 for y in ys):
        print("\n  FAIL: non-positive (D-kd) or W — cannot fit log-log.")
        return False

    exponent, b, r2 = _loglog_fit(xs, ys)
    C = math.exp(b)  # W = C·(D-kd)^exponent  (lumped prefactor)
    print(f"\n  fitted exponent = {exponent:.3f}   (target {EXPONENT_2D:.2f}, tol ±{EXP_TOL})")
    print(f"  log-log R^2     = {r2:.4f}   (min {R2_MIN})")
    print(f"  lumped prefactor C·ρ_b·√g = {C:.3e}")

    # W -> 0 near D ≈ k·d: the smallest-D point should sit well below extrapolation
    # to D-kd -> 0 (a monotone-rising curve through the origin). Implicit in the
    # power-law fit with positive exponent; we check monotonicity instead.
    mono = all(ys[i] < ys[i + 1] for i in range(len(ys) - 1))

    ok = (abs(exponent - EXPONENT_2D) <= EXP_TOL) and (r2 >= R2_MIN) and mono
    if not mono:
        print("  FAIL: W is not monotonically increasing with D.")
    print("\nRESULT:", "PASS" if ok else "FAIL")
    return ok


def plot(rows):
    os.makedirs(PLOT_DIR, exist_ok=True)
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    plt.rcParams.update({"figure.dpi": 150, "savefig.dpi": 150, "font.size": 11})

    rows = sorted(rows, key=lambda r: r["D"])
    xs = [r["D_eff"] for r in rows]
    ys = [r["W"] for r in rows]
    exponent, b, r2 = _loglog_fit(xs, ys)
    C = math.exp(b)

    # ── W vs (D - kd) on log-log with the fitted power law ──
    fig, ax = plt.subplots(figsize=(6.5, 4.5))
    ax.loglog(xs, ys, "o", ms=8, label="DIRT (steady slope)")
    xfit = [min(xs) * 0.9, max(xs) * 1.1]
    ax.loglog(xfit, [C * x ** exponent for x in xfit], "k--",
              label=fr"fit: $W\propto(D-kd)^{{{exponent:.2f}}}$")
    # 3/2 reference anchored at the middle point.
    mid = rows[len(rows) // 2]
    c32 = mid["W"] / mid["D_eff"] ** EXPONENT_2D
    ax.loglog(xfit, [c32 * x ** EXPONENT_2D for x in xfit], ":", color="gray",
              label=r"Beverloo $3/2$ slope")
    ax.set_xlabel(r"$D - k\,d$  (m)")
    ax.set_ylabel(r"steady mass-flow rate  $W$  (kg/s)")
    ax.set_title(fr"Beverloo 2D slot — exponent {exponent:.2f} ($R^2$={r2:.3f})")
    ax.legend()
    ax.grid(True, which="both", ls=":", alpha=0.4)
    fig.tight_layout()
    fig.savefig(os.path.join(PLOT_DIR, "beverloo_W_vs_D.png"))
    plt.close(fig)

    # ── cumulative discharged mass vs time, one curve per D ──
    fig, ax = plt.subplots(figsize=(6.5, 4.5))
    for r in rows:
        curve = _load_curve(r["D"])
        if not curve:
            continue
        t = [p[0] for p in curve]
        m = [p[1] for p in curve]
        ax.plot(t, m, "-", label=f"D = {r['D']*1e3:.0f} mm")
    ax.set_xlabel("time since orifice opened  (s)")
    ax.set_ylabel("cumulative discharged mass  (kg)")
    ax.set_title("Hopper discharge curves (steady slope = W)")
    ax.legend()
    ax.grid(True, ls=":", alpha=0.4)
    fig.tight_layout()
    fig.savefig(os.path.join(PLOT_DIR, "discharge_curves.png"))
    plt.close(fig)

    print(f"\nFigures -> {PLOT_DIR}/beverloo_W_vs_D.png, discharge_curves.png")


def graph():
    rows = _load_sweep()
    if not rows:
        print(f"No {SWEEP_CSV} — run 'start' first.")
        return False
    ok = validate(rows)
    plot(rows)
    return ok


# ── dispatch ─────────────────────────────────────────────────────────────────
def main():
    cmd = sys.argv[1] if len(sys.argv) > 1 else "all"
    if cmd == "generate":
        generate()
    elif cmd == "start":
        start()
    elif cmd == "graph":
        sys.exit(0 if graph() else 1)
    elif cmd == "all":
        generate()
        start()
        print()
        sys.exit(0 if graph() else 1)
    else:
        print(f"Unknown command: {cmd!r}")
        print("Usage: sweep.py [generate|start|graph]   (no arg = all three)")
        sys.exit(2)


if __name__ == "__main__":
    main()
