//! monkey_shear — constant-volume Lees–Edwards volume-fraction shear campaign
//! for three particle shapes at a COMMON equivalent-volume diameter D_eq = 0.1 m.
//!
//! One binary drives all three particle types (chosen entirely by the TOML
//! config passed on the command line):
//!   * **sphere** — a single sphere (radius 0.05 m).
//!   * **rigid**  — the 44-sub-sphere "monkey" as a rigid `[[clump.insert]]` body.
//!   * **bpm**    — the same monkey as a bonded-particle model: 44 free sub-spheres
//!                  per monkey (`source = "file"` CSV), welded INTRA-monkey by
//!                  `auto_bond` at setup. Monkeys are placed with a gap so no two
//!                  monkeys' sub-spheres are close enough to bond.
//!
//! Protocol (3 `[[run]]` stages, cf. `examples/bench_lebc_shear/config.toml`):
//! loose insert → settle → isotropic `erate` compress to the final 2×2×1 box
//! (Φ target; skipped when Φ ≤ the insertion cap) → Lees–Edwards `xy erate`
//! constant-volume shear (strain ≈ 2). Fully periodic, gravity off; flow = x,
//! gradient = y, vorticity = z.
//!
//! The recorder is reused **verbatim** from `examples/bench_lebc_shear/main.rs`:
//! each thermo interval it streams the full stress tensor → p, τ, N₁, N₂, the
//! shear-profile-subtracted granular temperature T, and the solid fraction Φ to
//! `<output_dir>/lebc_shear_results.csv`.
//!
//! Configs are generated by `tools/gen_series.py`. Run one:
//! ```bash
//! cargo run --release --example monkey_shear --no-default-features \
//!     --features precision-double -- examples/monkey_shear/configs/bpm/phi_0.1.toml
//! ```

use std::fs;
use std::io::Write as IoWrite;
use std::sync::Once;

use dirt_core::dirt_atom::DemAtom;
use dirt_core::prelude::*;
use dirt_core::soil_core::Accum;

fn main() {
    let mut app = App::new();
    app.add_plugins(CorePlugins)
        .add_plugins(GranularDefaultPlugins)
        .add_plugins(GravityPlugin) // gravity is set to 0 in config; kept for generality
        .add_plugins(FixesPlugin) // viscous damping / fixes for the settle stage
        .add_plugins(DeformPlugin) // isotropic compress + Lees–Edwards xy shear driver
        .add_plugins(ClumpPlugin) // rigid-monkey [[clump.insert]] bodies
        .add_plugins(DemBondPlugin); // bpm intra-monkey auto_bond welds

    // The `sphere` and `bpm` configs insert plain (non-clump) atoms, so the
    // ClumpPlugin's per-atom `ClumpAtom` columns are never populated for them
    // (they only grow during `[[clump.insert]]`). Left empty, the first spatial
    // re-sort calls `apply_permutation` on a zero-length column and panics. Pad
    // the columns to `nlocal` with the "not in a clump" sentinel (body_id = 0)
    // right after insertion — a no-op for the `rigid` config, where every atom
    // is already a clump sub-sphere. Kept in the example (one binary, three
    // configs) rather than the library core.
    app.add_setup_system(
        pad_clump_atom_columns
            .label("pad_clump_atom_columns")
            .after("clump_insert_atoms"),
        ScheduleSetupSet::Setup,
    );

    // Cool the pack during the (undamped) preparation stages only. The large
    // strain-controlled compression of a dense, tangling monkey pack pumps
    // collisional energy that, left undamped, heats into an overlap blow-up.
    // This mass-proportional viscous damping acts ONLY while the box is not
    // being sheared (xy streaming velocity ≈ 0 ⇒ settle + compress); the shear
    // stage runs fully undamped, so the measured rheology stays clean.
    app.add_update_system(damp_during_prep, ParticleSimScheduleSet::Force);

    app.add_update_system(record_shear, ParticleSimScheduleSet::PostFinalIntegration);
    // INVESTIGATION instrumentation (goal dirt-bpm-monkey-blowup-investigation):
    // per-thermo trace of bond count, largest bonded component (mis-weld check),
    // total KE, and — for the bpm type — the maximum CONTACT-ACTIVE (not 1-2/1-3
    // bond-excluded) INTRA-monkey sub-sphere overlap. Distinguishes intra-body
    // self-contact from inter-monkey collision as the origin of the overlap-guard
    // blow-up. Opt-in via the MONKEY_INSTRUMENT env var (off by default so the
    // campaign binary is unchanged); writes `<out>/instrument.csv`.
    app.add_update_system(
        instrument_blowup,
        ParticleSimScheduleSet::PostFinalIntegration,
    );
    app.start();
}

/// Per-thermo diagnostic for the bpm monkey blow-up investigation. Logs bond
/// count (breakage check — bonds are configured unbreakable), total kinetic
/// energy, granular-gas proxy, and the largest overlap among **contact-active**
/// (non 1-2/1-3-excluded) intra-monkey sub-sphere pairs. Sub-sphere → monkey
/// membership is the connected component of the bond graph (robust to tag order;
/// a component larger than one monkey would flag an auto_bond mis-weld).
/// Example-scoped; not a library concern.
fn instrument_blowup(
    atoms: Res<Atom>,
    registry: Res<AtomDataRegistry>,
    domain: Res<Domain>,
    run_state: Res<RunState>,
    comm: Res<CommResource>,
    input: Res<Input>,
) {
    // Opt-in: the campaign binary is unchanged unless MONKEY_INSTRUMENT is set,
    // so routine runs carry no per-thermo diagnostic cost or stderr noise.
    if std::env::var_os("MONKEY_INSTRUMENT").is_none() {
        return;
    }
    let step = run_state.total_cycle;
    if step % 2000 != 0 {
        return;
    }
    let nlocal = atoms.nlocal as usize;

    // Total kinetic energy Σ ½ m|v|².
    let mut ke = 0.0f64;
    for i in 0..nlocal {
        let m = atoms.mass[i] as f64;
        let v = atoms.vel[i];
        ke += 0.5 * m * (v[0] * v[0] + v[1] * v[1] + v[2] * v[2]) as f64;
    }

    let bond_store = registry.get::<BondStore>();
    let dem = registry.get::<DemAtom>();

    // Bond count (each undirected bond stored on both endpoints ⇒ halve).
    let nbonds: usize = match bond_store.as_ref() {
        Some(b) => {
            (0..nlocal.min(b.bonds.len()))
                .map(|i| b.bonds[i].len())
                .sum::<usize>()
                / 2
        }
        None => 0,
    };

    // Largest contact-active intra-monkey overlap ratio (sr - d)/sr, and count of
    // active intra-monkey pairs currently overlapping. Only meaningful for bpm.
    // Monkey membership is the connected component of the BOND GRAPH (robust to
    // tag ordering, and detects mis-welds: a component > 44 ⇒ auto_bond joined
    // two monkeys). Single-rank run ⇒ every sub-sphere and its partners are local.
    let (mut max_active_intra, mut n_active_overlap, mut max_component) = (0.0f64, 0usize, 0usize);
    if let (Some(ref bonds), Some(ref dem)) = (bond_store.as_ref(), dem.as_ref()) {
        use std::collections::HashMap;
        // tag → local index (this rank).
        let mut tag_idx: HashMap<u32, usize> = HashMap::with_capacity(nlocal);
        for i in 0..nlocal {
            tag_idx.insert(atoms.tag[i], i);
        }
        // Union–find over the bond graph.
        let mut parent: Vec<usize> = (0..nlocal).collect();
        fn find(parent: &mut Vec<usize>, mut x: usize) -> usize {
            while parent[x] != x {
                parent[x] = parent[parent[x]];
                x = parent[x];
            }
            x
        }
        for i in 0..nlocal.min(bonds.bonds.len()) {
            for b in &bonds.bonds[i] {
                if let Some(&j) = tag_idx.get(&b.partner_tag) {
                    let (ri, rj) = (find(&mut parent, i), find(&mut parent, j));
                    if ri != rj {
                        parent[ri] = rj;
                    }
                }
            }
        }
        let mut groups: HashMap<usize, Vec<usize>> = HashMap::new();
        for i in 0..nlocal {
            let r = find(&mut parent, i);
            groups.entry(r).or_default().push(i);
        }
        max_component = groups.values().map(|v| v.len()).max().unwrap_or(0);
        let size = domain.size;
        let pflags = domain.periodic_flags();
        for idxs in groups.values() {
            for a in 0..idxs.len() {
                for b in (a + 1)..idxs.len() {
                    let (i, j) = (idxs[a], idxs[b]);
                    if bonds.are_excluded(i, j, &atoms.tag) {
                        continue; // 1-2 / 1-3 excluded ⇒ no contact force
                    }
                    let mut d = [
                        atoms.pos[j][0] as f64 - atoms.pos[i][0] as f64,
                        atoms.pos[j][1] as f64 - atoms.pos[i][1] as f64,
                        atoms.pos[j][2] as f64 - atoms.pos[i][2] as f64,
                    ];
                    for k in 0..3 {
                        if pflags[k] {
                            d[k] -= size[k] * (d[k] / size[k]).round();
                        }
                    }
                    let dist = (d[0] * d[0] + d[1] * d[1] + d[2] * d[2]).sqrt();
                    let sr = (dem.radius[i] + dem.radius[j]) as f64;
                    if dist < sr {
                        let ratio = (sr - dist) / sr;
                        n_active_overlap += 1;
                        if ratio > max_active_intra {
                            max_active_intra = ratio;
                        }
                    }
                }
            }
        }
    }

    // Reduce scalars across ranks.
    let ke = comm.all_reduce_sum_f64(ke);
    let nbonds = comm.all_reduce_sum_f64(nbonds as f64) as usize;
    let n_active_overlap = comm.all_reduce_sum_f64(n_active_overlap as f64) as usize;
    let max_component = comm.all_reduce_sum_f64(max_component as f64) as usize; // single-rank
    let max_active_intra = comm.all_reduce_sum_f64(max_active_intra); // rank-0 only writes; single-rank runs

    if comm.rank() != 0 {
        return;
    }
    let sheared = domain.boundary_vel[0].abs() > 1e-12;
    let stage = if sheared { "shear" } else { "prep" };
    let out_dir = input
        .output_dir
        .clone()
        .unwrap_or_else(|| "examples/monkey_shear/data".to_string());
    let path = format!("{}/instrument.csv", out_dir);
    static INIT: Once = Once::new();
    INIT.call_once(|| {
        fs::create_dir_all(&out_dir).ok();
        if let Ok(mut f) = fs::File::create(&path) {
            writeln!(
                f,
                "step,stage,nbonds,max_bond_component,KE,max_active_intra_overlap,n_active_intra_overlaps"
            )
            .ok();
        }
    });
    if let Ok(mut f) = fs::OpenOptions::new().append(true).open(&path) {
        writeln!(
            f,
            "{},{},{},{},{:.6e},{:.6e},{}",
            step, stage, nbonds, max_component, ke, max_active_intra, n_active_overlap
        )
        .ok();
    }
    eprintln!(
        "[instr] step={} stage={} nbonds={} max_component={} KE={:.4e} max_active_intra_overlap={:.4} n_active_intra={}",
        step, stage, nbonds, max_component, ke, max_active_intra, n_active_overlap
    );
}

/// Grow the `ClumpAtom` per-atom columns to `nlocal`, tagging any atom not
/// created by `[[clump.insert]]` as "not in a clump" (`body_id = 0`). The clump
/// integration systems already skip `body_id == 0` atoms, so this only makes the
/// column lengths consistent for the spatial-sort permutation.
fn pad_clump_atom_columns(atoms: Res<Atom>, registry: Res<AtomDataRegistry>) {
    let nlocal = atoms.nlocal as usize;
    if let Some(mut clump) = registry.get_mut::<ClumpAtom>() {
        while clump.body_id.len() < nlocal {
            clump.body_id.push(0.0);
        }
        while clump.body_offset.len() < nlocal {
            clump.body_offset.push([0.0; 3]);
        }
    }
}

/// Mass-proportional viscous damping `F_i = −(2 m_i/τ) v_i`, applied to every
/// atom only when the box is not shearing (settle + compress). For a rigid
/// clump this correctly damps the body COM velocity and spin (the sub-sphere
/// forces aggregate: `Σ m_i r_i = 0`), and for a bonded monkey it bleeds the
/// network's collisional energy — without touching the shear stage.
fn damp_during_prep(mut atoms: ResMut<Atom>, domain: Res<Domain>) {
    // Non-zero xy streaming velocity ⇒ Lees–Edwards shear stage: leave undamped.
    if domain.boundary_vel[0].abs() > 1e-12 {
        return;
    }
    let nlocal = atoms.nlocal as usize;
    let dt = atoms.dt;
    if dt <= 0.0 {
        return;
    }
    let two_over_tau = 2.0 / 0.004; // damp velocity over τ≈4 ms (mild: allows rearrangement)
    for i in 0..nlocal {
        let g = two_over_tau * atoms.mass[i];
        for k in 0..3 {
            atoms.force[i][k] -= (g * atoms.vel[i][k] as f64) as Accum;
        }
    }
}

/// Record the steady-shear stress tensor, granular temperature, and solid fraction.
///
/// Reused verbatim from `examples/bench_lebc_shear/main.rs`.
fn record_shear(
    atoms: Res<Atom>,
    registry: Res<AtomDataRegistry>,
    domain: Res<Domain>,
    virial: Option<Res<VirialStress>>,
    run_state: Res<RunState>,
    comm: Res<CommResource>,
    input: Res<Input>,
) {
    let step = run_state.total_cycle;
    if step % 2000 != 0 {
        return;
    }

    let nlocal = atoms.nlocal as usize;
    let vol = domain.volume;
    if vol <= 0.0 {
        return;
    }

    // Shear rate γ̇ = Δv / L_y (0 during the settle stage → no profile subtraction).
    let ly = domain.size[1];
    let gdot = if ly > 0.0 {
        domain.boundary_vel[0] / ly
    } else {
        0.0
    };
    let y_lo = domain.boundaries_low[1];
    let y_hi = domain.boundaries_high[1];
    let yc = 0.5 * (y_lo + y_hi);

    // ── Kinetic stress + granular temperature (streaming velocity removed) ──
    // v'(i) = v(i) − γ̇·(y_i − y_center) x̂. Kinetic stress σ_kin = Σ m v'⊗v' / V.
    let mut kin = [0.0f64; 6]; // xx, yy, zz, xy, xz, yz
    let mut ke_fluct = 0.0f64; // Σ m |v'|²
    let mut m_total = 0.0f64;
    let mut vol_solid = 0.0f64;
    let dem = registry.get::<DemAtom>();
    for i in 0..nlocal {
        let m = atoms.mass[i];
        m_total += m;
        let vx = atoms.vel[i][0] - gdot * (atoms.pos[i][1] - yc);
        let vy = atoms.vel[i][1];
        let vz = atoms.vel[i][2];
        kin[0] += m * vx * vx;
        kin[1] += m * vy * vy;
        kin[2] += m * vz * vz;
        kin[3] += m * vx * vy;
        kin[4] += m * vx * vz;
        kin[5] += m * vy * vz;
        ke_fluct += m * (vx * vx + vy * vy + vz * vz);
        if let Some(ref dem) = dem {
            let r = dem.radius[i];
            vol_solid += (4.0 / 3.0) * std::f64::consts::PI * r * r * r;
        }
    }

    // ── Contact (Love–Weber) virial: σ_contact_ij = −VirialStress_ij / V ──
    let vir = match virial.as_ref() {
        Some(v) => [v.xx, v.yy, v.zz, v.xy, v.xz, v.yz],
        None => [0.0; 6],
    };

    // Reduce across ranks.
    let mut acc = [
        kin[0], kin[1], kin[2], kin[3], kin[4], kin[5], vir[0], vir[1], vir[2], vir[3], vir[4],
        vir[5], ke_fluct, m_total, vol_solid,
    ];
    for a in acc.iter_mut() {
        *a = comm.all_reduce_sum_f64(*a);
    }
    let (kin, vir) = (
        [acc[0], acc[1], acc[2], acc[3], acc[4], acc[5]],
        [acc[6], acc[7], acc[8], acc[9], acc[10], acc[11]],
    );
    let ke_fluct = acc[12];
    let m_total = acc[13];
    let vol_solid = acc[14];

    // Total stress σ = kinetic + contact. Contact part flips sign of the virial.
    let mut sig = [0.0f64; 6];
    for k in 0..6 {
        sig[k] = (kin[k] - vir[k]) / vol;
    }
    let p = (sig[0] + sig[1] + sig[2]) / 3.0;
    let n1 = sig[0] - sig[1];
    let n2 = sig[1] - sig[2];
    // von Mises shear stress τ = sqrt(½ σ':σ') from the deviator σ'.
    let dxx = sig[0] - p;
    let dyy = sig[1] - p;
    let dzz = sig[2] - p;
    let tau = (0.5 * (dxx * dxx + dyy * dyy + dzz * dzz)
        + sig[3] * sig[3]
        + sig[4] * sig[4]
        + sig[5] * sig[5])
        .sqrt();
    // Granular temperature T = (1/3) Σ m|v'|² / Σ m.
    let t_gran = if m_total > 0.0 {
        ke_fluct / (3.0 * m_total)
    } else {
        0.0
    };
    let phi = vol_solid / vol;

    if comm.rank() != 0 {
        return;
    }

    let time = step as f64 * atoms.dt;
    let out_dir = input
        .output_dir
        .clone()
        .unwrap_or_else(|| "examples/bench_lebc_shear/data".to_string());
    let path = format!("{}/lebc_shear_results.csv", out_dir);

    static INIT: Once = Once::new();
    INIT.call_once(|| {
        fs::create_dir_all(&out_dir).ok();
        let mut f = fs::File::create(&path).expect("cannot create lebc_shear_results.csv");
        writeln!(
            f,
            "step,time,gdot,sxx,syy,szz,sxy,sxz,syz,p,tau,N1,N2,T,phi"
        )
        .unwrap();
    });

    let mut f = fs::OpenOptions::new()
        .append(true)
        .open(&path)
        .expect("cannot open results csv");
    writeln!(
        f,
        "{},{:.8e},{:.8e},{:.8e},{:.8e},{:.8e},{:.8e},{:.8e},{:.8e},{:.8e},{:.8e},{:.8e},{:.8e},{:.8e},{:.8e}",
        step, time, gdot, sig[0], sig[1], sig[2], sig[3], sig[4], sig[5], p, tau, n1, n2, t_gran, phi
    )
    .unwrap();
}
