#!/usr/bin/env python3
"""
Lees–Edwards homogeneous simple-shear rheometer — Tier-1 DEM calibration.

A triperiodic box of glass beads (gravity off) is sheared at constant rate γ̇ via
the native Lees–Edwards triclinic deform style. Each run is held at fixed volume
(fixed Φ) while γ̇ is swept; in steady state the recorder reports the stress
tensor, granular temperature T, and Φ. From these we form the inertial number
I = γ̇·d·√(ρ_s/P), the friction μ = |σ_xy|/P, and Φ(I), and fit the μ(I) law that
the MUD SPH solver consumes.

Two sweeps:
  • production  — frictional grains (μ_p = 0.5, e = 0.7): fits μ(I), Φ(I).
  • kt          — frictionless grains (μ_p = 0, e = 0.7): validated against
                  granular kinetic theory (Lun et al. 1984 pressure equation of
                  state, and Bagnold γ̇²-scaling), which is exact for smooth
                  inelastic spheres in the collisional regime.

Commands (from anywhere):
    python3 examples/bench_lebc_shear/sweep.py generate   # write per-case configs
    python3 examples/bench_lebc_shear/sweep.py start      # build + run all cases
    python3 examples/bench_lebc_shear/sweep.py graph      # average, validate, fit, plot
    python3 examples/bench_lebc_shear/sweep.py            # all three, in order

Outputs:
    sweep/<case>/config.toml                 per-case configs        (gitignored)
    data/<case>/lebc_shear_results.csv       per-case time series    (gitignored)
    data/calibration.yaml                    μ(I)/Φ(I) fit → MUD     (gitignored)
    plots/mu_of_I.png, phi_of_I.png, kt_validation.png               (tracked)

References: GDR MiDi 2004; da Cruz et al. 2005 (I-scaling);
Lun, Savage, Jeffrey & Chepurniy, JFM 140 (1984) (KT transport coefficients).
"""

import os
import sys
import csv
import math
import subprocess

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))
EXAMPLE = "bench_lebc_shear"

DATA_DIR = os.path.join(SCRIPT_DIR, "data")
SWEEP_DIR = os.path.join(SCRIPT_DIR, "sweep")
PLOT_DIR = os.path.join(SCRIPT_DIR, "plots")

# ── Physics (shared with config.toml) ────────────────────────────────────────
L_FINAL = 0.006           # target (sheared) cubic box side [m]
PHI_LOOSE = 0.30          # insertion density (random insertion saturates ≈0.38)
RMIN, RMAX = 0.000225, 0.000275   # uniform radius [m] → d ≈ 0.5 mm
DENSITY = 2500.0          # kg/m^3 (ρ_s)
YOUNGS_MOD = 7.0e7         # softened from ~65 GPa real glass (rigid-grain limit)
POISSON = 0.245            # glass
RESTITUTION = 0.926        # measured glass–glass COR (canonical glass-bead material)
DT = 2.0e-7
SETTLE_STEPS = 20_000
COMPRESS_STEPS = 60_000   # quasi-static compaction loose → target Φ
# Shear duration is set by total STRAIN, not a fixed step count: strain = γ̇·dt·steps,
# so a fixed step count gives almost no strain at low γ̇. Steady state needs strain ≫ 1
# (also to dissipate the compression heat), so steps = TARGET_STRAIN/(γ̇·dt).
TARGET_STRAIN = 70.0   # near-elastic (e=0.95) KT sub-sweep equilibrates slowly; match the references (cutoff 40)
MIN_SHEAR_STEPS = 40_000
THERMO = 2000

D_MEAN = RMIN + RMAX                       # mean diameter (= 2·mean radius) [m]
R3_MEAN = (RMAX**4 - RMIN**4) / (4.0 * (RMAX - RMIN))   # <r³> for uniform radius
V_PARTICLE = (4.0 / 3.0) * math.pi * R3_MEAN            # mean particle volume

# ── Sweep grid ───────────────────────────────────────────────────────────────
# Target Φ reached by compressing a loose insert; γ̇ swept per Φ to span I.
# Dense Φ (≳0.4) is unreachable by random insertion alone, hence the compress stage.
PHI_GRID = [0.025, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5]
GDOT_GRID = [100.0]   # single shear rate for the KT stress-vs-Φ line

SWEEPS = {
    "production": dict(friction=0.16, e=RESTITUTION),   # canonical glass-bead μ_p
    # KT sub-sweep at e=0.95 to match the reference codes (Fortran/LIGGGHTS/LAMMPS
    # in ../lammps_shear_cell are all frictionless, e=0.95) for a like-for-like
    # cross-code comparison on the KT validation plot.
    "kt":         dict(friction=0.0, e=0.95),
}


def count_for_phi(phi):
    """Particle count to reach target Φ in the final (sheared) box."""
    return max(1, round(phi * L_FINAL**3 / V_PARTICLE))


def loose_box(count):
    """Initial box side so `count` particles sit at PHI_LOOSE before compression."""
    return (count * V_PARTICLE / PHI_LOOSE) ** (1.0 / 3.0)


def case_name(sweep, phi, gdot):
    return f"{sweep}_phi{phi:.2f}_g{gdot:g}"


def all_cases():
    for sweep, mat in SWEEPS.items():
        for phi in PHI_GRID:
            for gdot in GDOT_GRID:
                yield sweep, phi, gdot, mat


# ── config.toml template ─────────────────────────────────────────────────────
CONFIG_TEMPLATE = """\
# Auto-generated by sweep.py — Lees–Edwards shear, case {case}.
# Stages: settle (loose) → compress (loose box L_init → target box L_final, i.e.
# Φ_loose → Φ_target) → shear (Lees–Edwards xy at fixed target volume).
[comm]
processors_x = 1
processors_y = 1
processors_z = 1

[domain]
x_low = 0.0
x_high = {l_init}
y_low = 0.0
y_high = {l_init}
z_low = 0.0
z_high = {l_init}
boundary_x = "periodic"
boundary_y = "periodic"
boundary_z = "periodic"

[neighbor]
skin_fraction = 1.2
bin_size = {bin_size}
every = 1

[gravity]
gx = 0.0
gy = 0.0
gz = 0.0

[dem]
contact_model = "hertz"

[[dem.materials]]
name = "glass"
youngs_mod = {E}
poisson_ratio = {nu}
restitution = {e}
friction = {mu_p}

[[particles.insert]]
material = "glass"
count = {count}
radius = {{ distribution = "uniform", min = {rmin}, max = {rmax} }}
density = {density}
velocity = 0.02
region = {{ type = "block", min = [0.0, 0.0, 0.0], max = [{l_init}, {l_init}, {l_init}] }}
seed = 12345

[output]
dir = "{out_dir}"

[[run]]
name = "settle"
steps = {settle}
thermo = {thermo}
dt = {dt}

# Compress the loose pack down to the target box (→ target Φ), atoms remapped
# affinely. Velocity-style ramp reaches L_final deterministically at stage end:
# each box length goes L_init → L_final at v = (L_final − L_init)/(dt·steps).
[[run]]
name = "compress"
steps = {compress}
thermo = {thermo}
dt = {dt}
deform = {{ x = {{ style = "vel", velocity = {compress_vel} }}, y = {{ style = "vel", velocity = {compress_vel} }}, z = {{ style = "vel", velocity = {compress_vel} }} }}

# Lees–Edwards simple shear at fixed target volume.
[[run]]
name = "shear"
steps = {shear}
thermo = {thermo}
dt = {dt}
deform = {{ xy = {{ style = "erate", rate = {gdot} }} }}
"""


def generate():
    os.makedirs(SWEEP_DIR, exist_ok=True)
    n = 0
    for sweep, phi, gdot, mat in all_cases():
        case = case_name(sweep, phi, gdot)
        cdir = os.path.join(SWEEP_DIR, case)
        os.makedirs(cdir, exist_ok=True)
        out_dir = os.path.join(DATA_DIR, case)
        count = count_for_phi(phi)
        l_init = loose_box(count)
        # Deterministic ramp L_init → L_final over the compress stage (sign handles
        # both compaction, target Φ > Φ_loose, and dilation, target Φ < Φ_loose).
        compress_vel = (L_FINAL - l_init) / (DT * COMPRESS_STEPS)
        # Strain-based shear duration: reach TARGET_STRAIN regardless of γ̇.
        shear_steps = max(MIN_SHEAR_STEPS, round(TARGET_STRAIN / (gdot * DT)))
        cfg = CONFIG_TEMPLATE.format(
            case=case, l_init=l_init, l_final=L_FINAL, bin_size=1.2 * D_MEAN,
            E=YOUNGS_MOD, nu=POISSON, e=mat["e"], mu_p=mat["friction"], count=count,
            rmin=RMIN, rmax=RMAX, density=DENSITY, out_dir=out_dir,
            settle=SETTLE_STEPS, compress=COMPRESS_STEPS, shear=shear_steps,
            thermo=THERMO, dt=DT, gdot=gdot, compress_vel=compress_vel,
        )
        with open(os.path.join(cdir, "config.toml"), "w") as f:
            f.write(cfg)
        n += 1
    print(f"generated {n} case configs under {SWEEP_DIR}")


def build():
    print("building example (release)...")
    subprocess.run(
        ["cargo", "build", "--release", "--no-default-features", "--example", EXAMPLE],
        cwd=REPO_ROOT, check=True,
    )


def start():
    if not os.path.isdir(SWEEP_DIR):
        generate()
    build()
    exe = os.path.join(REPO_ROOT, "target", "release", "examples", EXAMPLE)
    for sweep, phi, gdot, mat in all_cases():
        case = case_name(sweep, phi, gdot)
        cfg = os.path.join(SWEEP_DIR, case, "config.toml")
        log = os.path.join(SWEEP_DIR, case, "run.log")
        print(f"running {case} ...")
        with open(log, "w") as lf:
            subprocess.run([exe, cfg], cwd=REPO_ROOT, stdout=lf, stderr=subprocess.STDOUT, check=True)
    print("all runs complete")


# ── Analysis ─────────────────────────────────────────────────────────────────
def read_shear_series(csv_path):
    """Read the shear-stage time series (gdot>0): strain (since shear start) and the
    Bagnold-normalized stresses + T*, for the convergence-to-steady-state diagnostic."""
    rows = [r for r in csv.DictReader(open(csv_path)) if float(r["gdot"]) > 0.0]
    if not rows:
        return None
    t0 = float(rows[0]["time"])
    out = dict(strain=[], p_bag=[], s_bag=[], Tstar=[])
    for r in rows:
        g = float(r["gdot"]); t = float(r["time"])
        bag = DENSITY * D_MEAN**2 * g * g
        out["strain"].append(g * (t - t0))
        out["p_bag"].append(float(r["p"]) / bag)
        out["s_bag"].append(abs(float(r["sxy"])) / bag)
        out["Tstar"].append(float(r["T"]) / (g * D_MEAN) ** 2)
    return out


def steady_average(csv_path, frac=0.5):
    """Average the steady-shear window: sheared rows (gdot>0) past `frac` of them.
    Also returns a `drift` = relative change of p between the two halves of that
    window — a steadiness indicator (small ⇒ plateaued)."""
    rows = [r for r in csv.DictReader(open(csv_path)) if float(r["gdot"]) > 0.0]
    if not rows:
        return None
    rows = rows[int(len(rows) * frac):]
    def avg(key, rs):
        return sum(float(r[key]) for r in rs) / len(rs)
    half = len(rows) // 2
    drift = float("nan")
    if half >= 1:
        p1, p2 = avg("p", rows[:half]), avg("p", rows[half:])
        if p1 != 0:
            drift = abs(p2 - p1) / abs(p1)
    return dict(
        gdot=avg("gdot", rows), p=avg("p", rows), sxy=avg("sxy", rows),
        syy=avg("syy", rows), tau=avg("tau", rows), T=avg("T", rows),
        phi=avg("phi", rows), drift=drift,
    )


def g0_cs(phi):
    """Carnahan–Starling radial distribution at contact."""
    return (2.0 - phi) / (2.0 * (1.0 - phi) ** 3)


def kt_p_star(phi, e):
    """Dimensionless KT normal stress p* = p/(ρ_s T) — a function of Φ (and e) only.
    Lun et al. (1984) EOS: p* = Φ[1 + 2(1+e)Φ g₀(Φ)]."""
    return phi * (1.0 + 2.0 * (1.0 + e) * phi * g0_cs(phi))


def kt_eta_star(phi, e):
    """Dimensionless KT shear viscosity η* = μ_s/(ρ_s d √T) = σ_xy/(ρ_s d √T γ̇),
    a function of Φ (and e) only. Lun et al. (1984) / Gidaspow (1994); the kinetic
    term reduces to the Chapman–Enskog dilute value 5√π/96 at Φ→0, e→1."""
    g0 = g0_cs(phi)
    eta_kin = (10.0 * math.sqrt(math.pi)) / (96.0 * (1.0 + e) * g0) \
        * (1.0 + (4.0 / 5.0) * (1.0 + e) * g0 * phi) ** 2
    eta_col = (4.0 / 5.0) * phi * phi * g0 * (1.0 + e) / math.sqrt(math.pi)
    return eta_kin + eta_col


def g0_ekt(phi, phi_max=0.636):
    """Extended-KT radial distribution (Berzi et al. 2020): Carnahan–Starling
    blended into the Torquato 2/(φ_max−φ) divergence near jamming. Ported verbatim
    from Liz's lammps_shear_cell/plot_all.py so the curves match the reference."""
    cs = g0_cs(phi)
    w = min(max((phi - 0.4) / (phi_max - 0.4), 0.0), 1.0) ** 2
    torquato = 2.0 / (phi_max - phi)
    return (1.0 - w) * cs + w * torquato


def gale_kt(phi, e, g0_func):
    """Closed-loop granular KT (Gale's lebc.py port, via plot_all.py): solves the
    homogeneous-shear energy balance and returns Bagnold-normalized
    (σ_xy*, σ_yy*, T*) = (σ_xy, p)/(ρ_s d² γ̇²) and T/(γ̇d)². `g0_func` selects
    standard Lun (Carnahan–Starling) or Extended KT (Berzi). Matches the reference
    script's KT lines exactly."""
    eta = 0.5 * (1.0 + e)
    g0 = g0_func(phi)
    T = 1.0
    F = (1.0 / (eta * (2.0 - eta) * g0)
         * (1.0 + (8.0 / 5.0) * eta * phi * g0)
         * (1.0 + (8.0 / 5.0) * eta * phi * g0 * (3.0 * eta - 2.0))
         + 768.0 * eta * phi * phi * g0 / (25.0 * math.pi))
    gamma = 48.0 / math.sqrt(math.pi) * eta * (1.0 - eta) * phi * phi * g0 * T ** 1.5
    pxy = math.sqrt(F * (5.0 / 96.0) * math.sqrt(math.pi * T) * gamma)
    dudy = gamma / pxy
    pressure = 2.0 * g0 * phi * phi * T * (1.0 + e) + phi * T
    ndcoeff = dudy * dudy
    return pxy / ndcoeff, pressure / ndcoeff, T / ndcoeff


# Standard Lun KT (Carnahan–Starling g₀), Bagnold-normalized — used for the
# DEM-vs-KT validation table and the primary curve.
def kt_sxy_bagnold(phi, e):
    return gale_kt(phi, e, g0_cs)[0]


def kt_p_bagnold(phi, e):
    return gale_kt(phi, e, g0_cs)[1]


def kt_T_star(phi, e):
    return gale_kt(phi, e, g0_cs)[2]


# ── Reference data: Fortran / LIGGGHTS / LAMMPS (../lammps_shear_cell) ─────────
# Frictionless spheres at e=0.95, γ̇=100, d=1mm, Bagnold-normalized σ/(ρ_p d² γ̇²).
REF_DIR = os.path.abspath(os.path.join(REPO_ROOT, "..", "lammps_shear_cell"))
REF_RHO, REF_D, REF_GDOT, REF_DT = 2500.0, 0.001, 100.0, 1.0e-7
REF_STRAIN_CUTOFF = 40.0
REF_NORM = REF_RHO * REF_D**2 * REF_GDOT**2

# Digitized from Liz's thesis Fig. 2.4.1 (sphere_KT.png) — shear stress only.
FORTRAN_PHI = [0.0257, 0.0502, 0.1004, 0.2007, 0.2990, 0.4000, 0.4997]
FORTRAN_SXY = [1.3599, 0.6897, 0.4125, 0.3675, 0.5760, 1.2103, 3.6268]
LIGGGHTS_PHI = [0.0492, 0.1410, 0.2308, 0.3189, 0.4089, 0.4997]
LIGGGHTS_SXY = [0.6480, 0.3486, 0.4096, 0.6674, 1.3138, 3.4658]


def load_references():
    """Return {'fortran','liggghts','lammps'} reference data (Bagnold-normalized).
    Fortran/LIGGGHTS are thesis-digitized shear stress; LAMMPS is read from
    ../lammps_shear_cell/run_phi*/stress_tensors.dat (shear + normal)."""
    refs = {"fortran": (FORTRAN_PHI, FORTRAN_SXY),
            "liggghts": (LIGGGHTS_PHI, LIGGGHTS_SXY),
            "lammps": ([], [], [])}
    for phi in [0.025, 0.05, 0.1, 0.2, 0.3, 0.4]:
        tag = f"run_phi{phi:.3f}".replace(".", "p")
        path = os.path.join(REF_DIR, tag, "stress_tensors.dat")
        if not os.path.isfile(path):
            continue
        steps, cxy, cyy, kxy, kyy = [], [], [], [], []
        for line in open(path):
            if line.startswith("#") or not line.strip():
                continue
            c = line.split()
            if len(c) < 13:
                continue
            steps.append(float(c[0]))
            cyy.append(float(c[2])); cxy.append(float(c[4]))
            kyy.append(float(c[8])); kxy.append(float(c[10]))
        if len(steps) < 10:
            continue
        s0 = steps[0]
        idx = [i for i, s in enumerate(steps) if (s - s0) * REF_DT * REF_GDOT >= REF_STRAIN_CUTOFF]
        if len(idx) < 5:
            continue
        sxy = sum(abs(cxy[i] + kxy[i]) for i in idx) / len(idx) / REF_NORM
        syy = sum((cyy[i] + kyy[i]) for i in idx) / len(idx) / REF_NORM
        refs["lammps"][0].append(phi)
        refs["lammps"][1].append(sxy)
        refs["lammps"][2].append(syy)
    return refs


def collect():
    """Read every case's steady average into a list of dicts."""
    out = []
    for sweep, phi_target, gdot, mat in all_cases():
        case = case_name(sweep, phi_target, gdot)
        csv_path = os.path.join(DATA_DIR, case, "lebc_shear_results.csv")
        if not os.path.isfile(csv_path):
            print(f"  (missing {case}, skipping)")
            continue
        s = steady_average(csv_path)
        if s is None or s["p"] <= 0.0:
            print(f"  ({case}: no steady data, skipping)")
            continue
        I = s["gdot"] * D_MEAN * math.sqrt(DENSITY / s["p"])
        mu = abs(s["sxy"]) / s["p"]
        out.append(dict(sweep=sweep, phi_target=phi_target, e=mat["e"], I=I, mu=mu, **s))
    return out


def fit_mu_of_I(points):
    """Least-squares fit μ(I) = μ_s + (μ2 − μ_s)/(I0/I + 1) via coarse grid search."""
    best = None
    for mu_s in [x / 100 for x in range(20, 50)]:
        for mu2 in [x / 100 for x in range(int(mu_s * 100), 100)]:
            for I0 in [0.05 * k for k in range(1, 21)]:
                err = 0.0
                for p in points:
                    pred = mu_s + (mu2 - mu_s) / (I0 / p["I"] + 1.0)
                    err += (pred - p["mu"]) ** 2
                if best is None or err < best[0]:
                    best = (err, mu_s, mu2, I0)
    return best[1], best[2], best[3]


def graph():
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib not available; skipping plots")
        plt = None

    os.makedirs(PLOT_DIR, exist_ok=True)
    pts = collect()
    if not pts:
        print("no data collected — run `start` first")
        return

    prod = [p for p in pts if p["sweep"] == "production"]
    kt = [p for p in pts if p["sweep"] == "kt"]

    # ── Steadiness: flag cases whose averaging window has not plateaued ──
    # `drift` = |Δp| between the two halves of the averaging window. Large drift
    # means steady state was not reached → increase TARGET_STRAIN (and inspect
    # plots/convergence.png, stress & T vs strain).
    print("\n=== Steady-state check (drift across averaging window) ===")
    not_steady = [p for p in pts if not (p.get("drift", 1.0) < 0.15)]
    for p in sorted(pts, key=lambda d: d.get("drift", 1.0), reverse=True)[:6]:
        flag = "OK" if p.get("drift", 1.0) < 0.15 else "NOT STEADY"
        print(f"  {p['sweep']:>10} Φ≈{p['phi_target']:.2f} γ̇={p['gdot']:.0f}: "
              f"p drift = {100*p.get('drift', float('nan')):.0f}%  {flag}")
    if not_steady:
        print(f"  ⚠ {len(not_steady)}/{len(pts)} cases not steady — raise TARGET_STRAIN; "
              f"see plots/convergence.png")
    else:
        print(f"  all {len(pts)} cases steady (drift < 15%)")

    # ── KT validation (frictionless): closed-loop Bagnold-normalized stress & T ──
    # T/(γ̇d)², p/(ρ_s d²γ̇²), σ_xy/(ρ_s d²γ̇²) are functions of Φ (and e) only (T is
    # set internally by production = dissipation), so every γ̇ collapses to one point
    # per Φ. This tests the EOS, viscosity AND dissipation together. T (hence both
    # stresses) DIVERGES ∝1/Φ² as Φ→0: vanishing dissipation can't balance shear
    # heating in a periodic box — so the lowest-Φ fixed-volume points are the
    # runaway/unsteady ones (pressure control is the clean route to dilute Φ).
    print("\n=== Kinetic-theory validation (frictionless sub-sweep) ===")
    print(f"  {'Φ':>6} {'γ̇':>7} {'T*_DEM':>9} {'T*_KT':>9} {'p_bag_DEM':>10} {'p_bag_KT':>10} {'p_rat':>6} "
          f"{'s_bag_DEM':>10} {'s_bag_KT':>10} {'s_rat':>6}")
    p_ok = s_ok = 0
    for p in sorted(kt, key=lambda d: (d["phi"], d["gdot"])):
        bag = DENSITY * D_MEAN**2 * p["gdot"]**2
        Tstar_dem = p["T"] / (p["gdot"] * D_MEAN) ** 2
        p_bag_dem = p["p"] / bag
        s_bag_dem = abs(p["sxy"]) / bag
        Tstar_kt = kt_T_star(p["phi"], p["e"])
        p_bag_kt = kt_p_bagnold(p["phi"], p["e"])
        s_bag_kt = kt_sxy_bagnold(p["phi"], p["e"])
        p_r = p_bag_dem / p_bag_kt if p_bag_kt > 0 else float("nan")
        s_r = s_bag_dem / s_bag_kt if s_bag_kt > 0 else float("nan")
        p_ok += 0.85 <= p_r <= 1.15
        s_ok += 0.80 <= s_r <= 1.20
        print(f"  {p['phi']:6.3f} {p['gdot']:7.0f} {Tstar_dem:9.3e} {Tstar_kt:9.3e} "
              f"{p_bag_dem:10.3e} {p_bag_kt:10.3e} {p_r:6.2f} "
              f"{s_bag_dem:10.3e} {s_bag_kt:10.3e} {s_r:6.2f}")
    if kt:
        pv = "PASS" if p_ok >= 0.6 * len(kt) else "FAIL"
        sv = "PASS" if s_ok >= 0.6 * len(kt) else "FAIL"
        print(f"  normal stress p/(ρ_s d²γ̇²):  {p_ok}/{len(kt)} within 15%  → {pv}")
        print(f"  shear stress σ_xy/(ρ_s d²γ̇²): {s_ok}/{len(kt)} within 20%  → {sv}")

    # ── Bagnold scaling check (fixed Φ): p/γ̇² and σ_xy/γ̇² ~ const ──
    print("\n=== Bagnold scaling (σ ∝ γ̇²) — production, per Φ ===")
    for phi_t in sorted(set(p["phi_target"] for p in prod)):
        grp = sorted([p for p in prod if p["phi_target"] == phi_t], key=lambda d: d["gdot"])
        if len(grp) < 2:
            continue
        ratios = [p["p"] / p["gdot"] ** 2 for p in grp]
        spread = (max(ratios) - min(ratios)) / (sum(ratios) / len(ratios))
        print(f"  Φ≈{phi_t:.2f}: p/γ̇² spread = {spread*100:.0f}% "
              f"({'Bagnold-like' if spread < 0.5 else 'rate-dependent'})")

    # ── μ(I), Φ(I) fit (production) ──
    if len(prod) >= 4:
        mu_s, mu2, I0 = fit_mu_of_I(prod)
        phi_max = max(p["phi"] for p in prod)
        rho_c = phi_max * DENSITY
        print("\n=== μ(I) / Φ(I) fit (frictional production sweep) ===")
        print(f"  μ_s = {mu_s:.3f}   μ_2 = {mu2:.3f}   I_0 = {I0:.3f}")
        print(f"  Φ_max = {phi_max:.3f}   ρ_c = Φ_max·ρ_s = {rho_c:.1f} kg/m³")

        os.makedirs(DATA_DIR, exist_ok=True)
        with open(os.path.join(DATA_DIR, "calibration.yaml"), "w") as f:
            f.write("# DEM-calibrated μ(I) closure for mud_constitutive::MaterialParams\n")
            f.write("material: glass_beads_dem\n")
            f.write(f"rho_s: {DENSITY}\n")
            f.write(f"d: {D_MEAN}\n")
            f.write(f"mu_s: {mu_s:.4f}\n")
            f.write(f"mu_2: {mu2:.4f}\n")
            f.write(f"I_0: {I0:.4f}\n")
            f.write(f"phi_max: {phi_max:.4f}\n")
            f.write(f"rho_c: {rho_c:.2f}\n")
        print(f"  wrote {os.path.join(DATA_DIR, 'calibration.yaml')}")
    else:
        mu_s = mu2 = I0 = None
        print("\n(need ≥4 production points for a μ(I) fit)")

    if plt is None:
        return

    # μ(I)
    fig, ax = plt.subplots(figsize=(6, 4.2))
    ax.scatter([p["I"] for p in prod], [p["mu"] for p in prod], c="tab:blue", label="DEM (frictional)")
    if mu_s is not None:
        xs = [10 ** (-4 + 0.05 * k) for k in range(80)]
        ax.plot(xs, [mu_s + (mu2 - mu_s) / (I0 / x + 1.0) for x in xs], "k-",
                label=f"fit: μ_s={mu_s:.2f}, μ_2={mu2:.2f}, I_0={I0:.2f}")
    ax.set_xscale("log"); ax.set_xlabel("inertial number I"); ax.set_ylabel("μ = |σ_xy| / P")
    ax.set_title("Lees–Edwards rheometer: μ(I)"); ax.legend(); ax.grid(True, alpha=0.3)
    fig.tight_layout(); fig.savefig(os.path.join(PLOT_DIR, "mu_of_I.png"), dpi=130); plt.close(fig)

    # Φ(I)
    fig, ax = plt.subplots(figsize=(6, 4.2))
    ax.scatter([p["I"] for p in prod], [p["phi"] for p in prod], c="tab:green")
    ax.set_xscale("log"); ax.set_xlabel("inertial number I"); ax.set_ylabel("Φ")
    ax.set_title("Lees–Edwards rheometer: Φ(I)"); ax.grid(True, alpha=0.3)
    fig.tight_layout(); fig.savefig(os.path.join(PLOT_DIR, "phi_of_I.png"), dpi=130); plt.close(fig)

    # KT validation: closed-loop Bagnold-normalized T and stresses vs Φ.
    # T is set internally by production = dissipation, so T/(γ̇d)², p/(ρ_s d²γ̇²) and
    # σ_xy/(ρ_s d²γ̇²) are functions of Φ (and e) only. KT is a continuous curve from
    # dilute Φ to RCP; DEM points (all γ̇ collapsed) overlay it. Note the 1/Φ²
    # divergence at low Φ (runaway heating in a periodic box) and the deviation
    # above KT toward jamming (Φ_c≈0.64), where enduring contacts dominate.
    if kt:
        e0 = kt[0]["e"]
        refs = load_references()
        phi_line = [0.02 + 0.005 * k for k in range(0, 121)]  # 0.02 → 0.62
        bag = lambda p: DENSITY * D_MEAN**2 * p["gdot"]**2
        fig, (axT, axp, axs) = plt.subplots(1, 3, figsize=(15, 4.4))

        # KT curves: standard Lun (CS g₀) and Extended KT (Berzi g₀).
        lun = [gale_kt(x, e0, g0_cs) for x in phi_line]
        ekt = [gale_kt(x, e0, g0_ekt) for x in phi_line]
        # DIRT realized COR vs nominal input (bench_hertz_rebound). With the exact
        # coeff_restitution damping (hertz_beta_for_cor) the realized COR ≈ nominal,
        # so this curve now coincides with the e0 curve and DIRT lands on the same
        # line as LAMMPS/LIGGGHTS. (Old Tsuji-polynomial damping realized 0.965 at
        # nominal 0.95 — a visibly separate line; kept here as a before/after marker.)
        REALIZED = {0.95: 0.950, 0.90: 0.902, 0.70: 0.717}
        e_real = REALIZED.get(round(e0, 2), e0)
        lun_real = [gale_kt(x, e_real, g0_cs) for x in phi_line]

        # ── granular temperature T* = T/(γ̇d)² ──
        axT.plot(phi_line, [v[2] for v in lun], "k--", lw=1.3, label=f"Lun KT (e={e0})")
        axT.plot(phi_line, [v[2] for v in ekt], "k-", lw=2, label="Extended KT (Berzi)")
        axT.plot(phi_line, [v[2] for v in lun_real], ":", c="tab:blue", lw=1.5, label=f"Lun KT (DIRT realized e={e_real})")
        axT.scatter([p["phi"] for p in kt], [p["T"] / (p["gdot"] * D_MEAN)**2 for p in kt],
                    c="tab:blue", marker="s", zorder=4, label="DIRT")
        axT.set_ylabel(r"$T/(\dot\gamma d)^2$"); axT.set_title("Granular temperature")

        # ── normal stress σ_yy/(ρ_s d²γ̇²) (references report σ_yy) ──
        axp.plot(phi_line, [v[1] for v in lun], "k--", lw=1.3, label=f"Lun KT (e={e0})")
        axp.plot(phi_line, [v[1] for v in ekt], "k-", lw=2, label="Extended KT (Berzi)")
        axp.plot(phi_line, [v[1] for v in lun_real], ":", c="tab:blue", lw=1.5, label=f"Lun KT (DIRT realized e={e_real})")
        axp.scatter([p["phi"] for p in kt], [p["syy"] / bag(p) for p in kt],
                    c="tab:blue", marker="s", zorder=4, label="DIRT")
        if refs["lammps"][0]:
            axp.scatter(refs["lammps"][0], refs["lammps"][2], c="tab:red", marker="^", zorder=3, label="LAMMPS")
        axp.set_ylabel(r"$\sigma_{yy}\,/\,\rho_s d^2 \dot\gamma^2$"); axp.set_title("Normal stress")

        # ── shear stress σ_xy/(ρ_s d²γ̇²) (all codes) ──
        axs.plot(phi_line, [v[0] for v in lun], "k--", lw=1.3, label=f"Lun KT (e={e0})")
        axs.plot(phi_line, [v[0] for v in ekt], "k-", lw=2, label="Extended KT (Berzi)")
        axs.plot(phi_line, [v[0] for v in lun_real], ":", c="tab:blue", lw=1.5, label=f"Lun KT (DIRT realized e={e_real})")
        axs.scatter([p["phi"] for p in kt], [abs(p["sxy"]) / bag(p) for p in kt],
                    c="tab:blue", marker="s", zorder=4, label="DIRT")
        if refs["lammps"][0]:
            axs.scatter(refs["lammps"][0], refs["lammps"][1], c="tab:red", marker="^", zorder=3, label="LAMMPS")
        axs.scatter(refs["fortran"][0], refs["fortran"][1], facecolors="none", edgecolors="tab:green", marker="o", zorder=3, label="Fortran LEBC")
        axs.scatter(refs["liggghts"][0], refs["liggghts"][1], c="tab:purple", marker="D", zorder=3, label="LIGGGHTS")
        axs.set_ylabel(r"$\sigma_{xy}\,/\,\rho_s d^2 \dot\gamma^2$"); axs.set_title("Shear stress")

        for ax in (axT, axp, axs):
            ax.set_xlabel("Φ"); ax.set_yscale("log"); ax.grid(True, alpha=0.3)
            ax.legend(fontsize=8); ax.set_xlim(0, 0.62); ax.axvline(0.64, ls=":", c="grey")
        fig.suptitle(f"KT validation (frictionless, e={e0}): DIRT vs LAMMPS / Fortran / LIGGGHTS / KT "
                     "(Bagnold-normalized vs Φ)")
        fig.tight_layout(); fig.savefig(os.path.join(PLOT_DIR, "kt_validation.png"), dpi=130); plt.close(fig)

    # ── Convergence diagnostic: stress & T vs strain, to confirm steady state ──
    # Each line is one case (KT sub-sweep); the averaging window (last 50% of the
    # shear strain) is shaded. Curves should plateau before entering it.
    fig, (axp, axT) = plt.subplots(1, 2, figsize=(11, 4.4))
    plotted = 0
    for sw, phi_t, gdot, mat in all_cases():
        if sw != "kt":
            continue
        series = read_shear_series(os.path.join(DATA_DIR, case_name(sw, phi_t, gdot), "lebc_shear_results.csv")) \
            if os.path.isfile(os.path.join(DATA_DIR, case_name(sw, phi_t, gdot), "lebc_shear_results.csv")) else None
        if not series or not series["strain"]:
            continue
        lbl = f"Φ≈{phi_t:.2f}, γ̇={gdot:g}"
        axp.plot(series["strain"], series["s_bag"], lw=1, label=lbl)
        axT.plot(series["strain"], series["Tstar"], lw=1, label=lbl)
        plotted += 1
    if plotted:
        smax = max(max(read_shear_series(os.path.join(DATA_DIR, case_name("kt", pt, g), "lebc_shear_results.csv"))["strain"])
                   for pt in PHI_GRID for g in GDOT_GRID
                   if os.path.isfile(os.path.join(DATA_DIR, case_name("kt", pt, g), "lebc_shear_results.csv")))
        for ax, ylab, title in ((axp, r"$\sigma_{xy}/\rho_s d^2\dot\gamma^2$", "Shear stress vs strain"),
                                (axT, r"$T/(\dot\gamma d)^2$", "Granular temperature vs strain")):
            ax.axvspan(smax * 0.5, smax, color="grey", alpha=0.15, label="averaging window")
            ax.set_xlabel("strain γ = γ̇·t"); ax.set_ylabel(ylab); ax.set_yscale("log")
            ax.set_title(title); ax.grid(True, alpha=0.3)
        axp.legend(fontsize=7, ncol=2)
        fig.suptitle("Convergence to steady state (frictionless cases)")
        fig.tight_layout(); fig.savefig(os.path.join(PLOT_DIR, "convergence.png"), dpi=130)
    plt.close(fig)

    print(f"\nplots written to {PLOT_DIR}")


def main():
    cmd = sys.argv[1] if len(sys.argv) > 1 else "all"
    if cmd == "generate":
        generate()
    elif cmd == "start":
        start()
    elif cmd == "graph":
        graph()
    elif cmd == "all":
        generate(); start(); graph()
    else:
        print(__doc__); sys.exit(1)


if __name__ == "__main__":
    main()
