//! Emit the mixed-material pair table built through DIRT's public typed API.
//!
//! The accompanying `sweep.py` compares this output with values generated by
//! the pre-redesign implementation.  Keeping the executable outside the
//! crate's unit-test module means the regression exercises the public API and
//! cannot pass by merely printing a test oracle.

use dirt_core::dirt_atom::{
    Adhesion, Elastic, Friction, LiquidBridge, Material, MaterialTable, Mdr, Rolling, Twisting,
};

fn main() {
    let mut table = MaterialTable::new();
    let soft = table
        .add(
            Material::new(
                "soft",
                Elastic::new(8.7e9, 0.30, 0.95).with_hooke_stiffness(1.0e6, 5.0e5),
            )
            .with_friction(Friction {
                sliding: 0.4,
                rolling: 0.1,
                twisting: 0.05,
            })
            .with_adhesion(Adhesion::SurfaceEnergy { energy: 0.2 })
            .with_rolling(Rolling::Sds {
                stiffness: 2.0,
                damping: 0.3,
            })
            .with_twisting(Twisting::Sds {
                stiffness: 3.0,
                damping: 0.4,
            })
            .with_mdr(Mdr {
                yield_stress: 1.0e6,
                psi_b: 0.1,
                damping: 0.02,
            })
            .with_liquid_bridge(LiquidBridge {
                volume: 1.0e-11,
                surface_tension: 0.072,
                contact_angle: 0.2,
                rupture_distance: 1.0e-4,
            }),
        )
        .expect("fixed validation material must be valid");
    let stiff = table
        .add(
            Material::new(
                "stiff",
                Elastic::new(70e9, 0.22, 0.80).with_hooke_stiffness(2.0e6, 7.0e5),
            )
            .with_friction(Friction {
                sliding: 0.3,
                rolling: 0.2,
                twisting: 0.07,
            })
            .with_adhesion(Adhesion::SurfaceEnergy { energy: 0.5 })
            .with_rolling(Rolling::Sds {
                stiffness: 4.0,
                damping: 0.6,
            })
            .with_twisting(Twisting::Sds {
                stiffness: 5.0,
                damping: 0.8,
            })
            .with_mdr(Mdr {
                yield_stress: 2.0e6,
                psi_b: 0.2,
                damping: 0.04,
            })
            .with_liquid_bridge(LiquidBridge {
                volume: 8.0e-12,
                surface_tension: 0.060,
                contact_angle: 0.4,
                rupture_distance: 2.0e-4,
            }),
        )
        .expect("fixed validation material must be valid");
    table.build_pair_tables();
    let (i, j) = (soft.index(), stiff.index());

    println!("property,value");
    for (name, value) in [
        ("beta", table.beta_ij[i][j]),
        ("friction", table.friction_ij[i][j]),
        ("rolling_friction", table.rolling_friction_ij[i][j]),
        ("cohesion_energy", table.cohesion_energy_ij[i][j]),
        ("surface_energy", table.surface_energy_ij[i][j]),
        ("twisting_friction", table.twisting_friction_ij[i][j]),
        ("e_eff", table.e_eff_ij[i][j]),
        ("g_eff", table.g_eff_ij[i][j]),
        ("kn", table.kn_ij[i][j]),
        ("kt", table.kt_ij[i][j]),
        ("rolling_stiffness", table.rolling_stiffness_ij[i][j]),
        ("rolling_damping", table.rolling_damping_ij[i][j]),
        ("twisting_stiffness", table.twisting_stiffness_ij[i][j]),
        ("twisting_damping", table.twisting_damping_ij[i][j]),
        ("mdr_yield_stress", table.mdr_yield_stress_ij[i][j]),
        ("mdr_psi_b", table.mdr_psi_b_ij[i][j]),
        ("mdr_damping", table.mdr_damping_ij[i][j]),
        ("liquid_volume", table.liquid_bridge_volume_ij[i][j]),
        (
            "liquid_surface_tension",
            table.liquid_surface_tension_ij[i][j],
        ),
        ("liquid_contact_angle", table.liquid_contact_angle_ij[i][j]),
        (
            "liquid_rupture_distance",
            table.liquid_rupture_distance_ij[i][j],
        ),
    ] {
        println!("{name},{value:.17e}");
    }
}
