#!/usr/bin/env python3
"""
Enduring-contact (rate-independent) stress branch — Tier-4 SPH glass-bead calibration.

A triperiodic box of glass beads (gravity off) is sheared at constant rate γ̇ via
the native Lees–Edwards triclinic deform style. Each run is held at fixed volume
(fixed Φ) and sheared with the canonical FRICTIONAL material (μ_p = 0.16); in
steady state the recorder reports the stress tensor, granular temperature T, and Φ.

DELIVERABLE — the enduring-contact stress branch σ_contact(Φ): the DENSE-regime
residual between the measured DEM pressure and the collisional kinetic-theory
(Lun et al. 1984) prediction evaluated at the *measured* granular temperature,

    σ_contact(Φ) ≈ p_DEM(Φ) − p_KT(Φ, T_measured),
    p_KT(Φ, T)  = ρ_s · T · p*(Φ, e),
    p*(Φ, e)    = Φ [ 1 + 2(1+e) Φ g₀(Φ) ]   (Lun EOS, Carnahan–Starling g₀).

p_KT is the part of the pressure that collisional kinetic theory explains given
the *measured* T and Φ; the residual p_DEM − p_KT is everything left over — the
rate-independent enduring-contact-network stress. It is ≈0 below Φ≈0.4 and grows
toward jamming (this gap was seen opening at Φ≈0.43 in bench_lebc_shear). It is
the rate-independent branch the granular-temperature de-fluidization model consumes.

Commands (from anywhere):
    python3 examples/SPH_glass_sphere_calibration/04_enduring_contact/sweep.py generate
    python3 examples/SPH_glass_sphere_calibration/04_enduring_contact/sweep.py start
    python3 examples/SPH_glass_sphere_calibration/04_enduring_contact/sweep.py graph
    python3 examples/SPH_glass_sphere_calibration/04_enduring_contact/sweep.py   # all three

Outputs:
    sweep/<case>/config.toml                       per-case configs        (gitignored)
    data/<case>/enduring_contact_results.csv       per-case time series    (gitignored)
    data/sigma_contact.csv                         σ_contact(Φ) table      (gitignored)
    plots/sigma_contact.png, stress_decomposition.png                     (tracked)

References: Lun, Savage, Jeffrey & Chepurniy, JFM 140 (1984) (KT EOS);
GDR MiDi 2004; da Cruz et al. 2005 (frictional dense shear).
"""

import os
import sys
import csv
import math
import subprocess

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", "..", ".."))
EXAMPLE = "sphcal_enduring_contact"

DATA_DIR = os.path.join(SCRIPT_DIR, "data")
SWEEP_DIR = os.path.join(SCRIPT_DIR, "sweep")
PLOT_DIR = os.path.join(SCRIPT_DIR, "plots")
SIGMA_CSV = os.path.join(DATA_DIR, "sigma_contact.csv")

# ── Canonical glass material (shared with config.toml) ────────────────────────
L_FINAL = 0.006           # target (sheared) cubic box side [m]
PHI_LOOSE = 0.30          # insertion density (random insertion saturates ≈0.38)
RMIN, RMAX = 0.000225, 0.000275   # uniform radius [m] → d ≈ 0.5 mm
DENSITY = 2500.0          # kg/m^3 (ρ_s)
YOUNGS_MOD = 7.0e7        # softened from ~65 GPa real glass (rigid-grain limit)
POISSON = 0.245           # glass
RESTITUTION = 0.926       # measured glass–glass COR (canonical glass-bead material)
FRICTION = 0.16           # measured glass–glass sliding μ_p (canonical)
ROLLING = 0.10            # measured glass-bead rolling friction μ_r (default "constant" model)
DT = 2.0e-7
SETTLE_STEPS = 20_000
COMPRESS_STEPS = 60_000   # quasi-static compaction loose → target Φ
# Shear duration is set by total STRAIN, not a fixed step count.
TARGET_STRAIN = 30.0
MIN_SHEAR_STEPS = 40_000
THERMO = 2000

D_MEAN = RMIN + RMAX                       # mean diameter (= 2·mean radius) [m]
R3_MEAN = (RMAX**4 - RMIN**4) / (4.0 * (RMAX - RMIN))   # <r³> for uniform radius
V_PARTICLE = (4.0 / 3.0) * math.pi * R3_MEAN            # mean particle volume

# ── Sweep grid ───────────────────────────────────────────────────────────────
# A single FRICTIONAL family across a Φ range that brackets the onset of the
# enduring-contact branch: from below it (σ_contact≈0) up toward jamming. Each Φ
# is reached by compressing a loose insert to the target box; γ̇ is fixed.
PHI_GRID = [0.30, 0.40, 0.45, 0.50, 0.55, 0.58, 0.60]
GDOT = 100.0


def count_for_phi(phi):
    """Particle count to reach target Φ in the final (sheared) box."""
    return max(1, round(phi * L_FINAL**3 / V_PARTICLE))


def loose_box(count):
    """Initial box side so `count` particles sit at PHI_LOOSE before compression."""
    return (count * V_PARTICLE / PHI_LOOSE) ** (1.0 / 3.0)


def case_name(phi):
    return f"phi{phi:.2f}"


def all_cases():
    for phi in PHI_GRID:
        yield phi


# ── config.toml template ─────────────────────────────────────────────────────
CONFIG_TEMPLATE = """\
# Auto-generated by sweep.py — Lees–Edwards frictional shear, case {case}.
# Stages: settle (loose) → compress (loose box L_init → target box L_final, i.e.
# Φ_loose → Φ_target) → shear (Lees–Edwards xy at fixed target volume).
[comm]
processors_x = 1
processors_y = 1
processors_z = 1

[domain]
x_low = 0.0
x_high = {l_init}
y_low = 0.0
y_high = {l_init}
z_low = 0.0
z_high = {l_init}
boundary_x = "periodic"
boundary_y = "periodic"
boundary_z = "periodic"

[neighbor]
skin_fraction = 1.2
bin_size = {bin_size}
every = 1

[gravity]
gx = 0.0
gy = 0.0
gz = 0.0

[dem]
contact_model = "hertz"

[[dem.materials]]
name = "glass"
youngs_mod = {E}
poisson_ratio = {nu}
restitution = {e}
friction = {mu_p}
rolling_friction = {mu_r}
# canonical density {density} kg/m³ is set per-insert below ([dem.materials] has no density field)

[[particles.insert]]
material = "glass"
count = {count}
radius = {{ distribution = "uniform", min = {rmin}, max = {rmax} }}
density = {density}
velocity = 0.02
region = {{ type = "block", min = [0.0, 0.0, 0.0], max = [{l_init}, {l_init}, {l_init}] }}
seed = 12345

[output]
dir = "{out_dir}"

[[run]]
name = "settle"
steps = {settle}
thermo = {thermo}
dt = {dt}

# Compress the loose pack down to the target box (→ target Φ), atoms remapped
# affinely. Velocity-style ramp reaches L_final deterministically at stage end:
# each box length goes L_init → L_final at v = (L_final − L_init)/(dt·steps).
[[run]]
name = "compress"
steps = {compress}
thermo = {thermo}
dt = {dt}
deform = {{ x = {{ style = "vel", velocity = {compress_vel} }}, y = {{ style = "vel", velocity = {compress_vel} }}, z = {{ style = "vel", velocity = {compress_vel} }} }}

# Lees–Edwards simple shear at fixed target volume.
[[run]]
name = "shear"
steps = {shear}
thermo = {thermo}
dt = {dt}
deform = {{ xy = {{ style = "erate", rate = {gdot} }} }}
"""


def generate():
    os.makedirs(SWEEP_DIR, exist_ok=True)
    n = 0
    for phi in all_cases():
        case = case_name(phi)
        cdir = os.path.join(SWEEP_DIR, case)
        os.makedirs(cdir, exist_ok=True)
        out_dir = os.path.join(DATA_DIR, case)
        count = count_for_phi(phi)
        l_init = loose_box(count)
        compress_vel = (L_FINAL - l_init) / (DT * COMPRESS_STEPS)
        shear_steps = max(MIN_SHEAR_STEPS, round(TARGET_STRAIN / (GDOT * DT)))
        cfg = CONFIG_TEMPLATE.format(
            case=case, l_init=l_init, bin_size=1.2 * D_MEAN,
            E=YOUNGS_MOD, nu=POISSON, e=RESTITUTION, mu_p=FRICTION, mu_r=ROLLING, count=count,
            rmin=RMIN, rmax=RMAX, density=DENSITY, out_dir=out_dir,
            settle=SETTLE_STEPS, compress=COMPRESS_STEPS, shear=shear_steps,
            thermo=THERMO, dt=DT, gdot=GDOT, compress_vel=compress_vel,
        )
        with open(os.path.join(cdir, "config.toml"), "w") as f:
            f.write(cfg)
        n += 1
    print(f"generated {n} case configs under {SWEEP_DIR}")


def build():
    print("building example (release)...")
    subprocess.run(
        ["cargo", "build", "--release", "--no-default-features", "--example", EXAMPLE],
        cwd=REPO_ROOT, check=True,
    )


def start():
    if not os.path.isdir(SWEEP_DIR):
        generate()
    build()
    exe = os.path.join(REPO_ROOT, "target", "release", "examples", EXAMPLE)
    for phi in all_cases():
        case = case_name(phi)
        cfg = os.path.join(SWEEP_DIR, case, "config.toml")
        log = os.path.join(SWEEP_DIR, case, "run.log")
        # Wipe stale results so an aborted/old run can never be re-plotted.
        old = os.path.join(DATA_DIR, case, "enduring_contact_results.csv")
        if os.path.isfile(old):
            os.remove(old)
        print(f"running {case} ...")
        with open(log, "w") as lf:
            subprocess.run([exe, cfg], cwd=REPO_ROOT, stdout=lf, stderr=subprocess.STDOUT, check=True)
    print("all runs complete")


# ── Kinetic-theory closure (Lun et al. 1984, Carnahan–Starling g₀) ────────────
def g0_cs(phi):
    """Carnahan–Starling radial distribution at contact."""
    return (2.0 - phi) / (2.0 * (1.0 - phi) ** 3)


def kt_p_star(phi, e):
    """Dimensionless KT normal stress p* = p/(ρ_s T) — a function of Φ (and e) only.
    Lun et al. (1984) EOS: p* = Φ[1 + 2(1+e)Φ g₀(Φ)]."""
    return phi * (1.0 + 2.0 * (1.0 + e) * phi * g0_cs(phi))


def kt_pressure(phi, T, e):
    """Collisional KT pressure at the MEASURED granular temperature T and Φ:
    p_KT = ρ_s · T · p*(Φ, e). This is what kinetic theory predicts the pressure
    *should* be given the observed agitation; the DEM excess over it is the
    enduring-contact branch."""
    return DENSITY * T * kt_p_star(phi, e)


# ── Analysis ─────────────────────────────────────────────────────────────────
def read_shear_series(csv_path):
    """Strain (since shear start) and p/T time series, for the convergence plot."""
    rows = [r for r in csv.DictReader(open(csv_path)) if float(r["gdot"]) > 0.0]
    if not rows:
        return None
    t0 = float(rows[0]["time"])
    out = dict(strain=[], p=[], T=[])
    for r in rows:
        g = float(r["gdot"]); t = float(r["time"])
        out["strain"].append(g * (t - t0))
        out["p"].append(float(r["p"]))
        out["T"].append(float(r["T"]))
    return out


def steady_average(csv_path, frac=0.5):
    """Average the steady-shear window (sheared rows past `frac`). `drift` = relative
    change of p between the window halves (small ⇒ plateaued)."""
    rows = [r for r in csv.DictReader(open(csv_path)) if float(r["gdot"]) > 0.0]
    if not rows:
        return None
    rows = rows[int(len(rows) * frac):]
    def avg(key, rs):
        return sum(float(r[key]) for r in rs) / len(rs)
    half = len(rows) // 2
    drift = float("nan")
    if half >= 1:
        p1, p2 = avg("p", rows[:half]), avg("p", rows[half:])
        if p1 != 0:
            drift = abs(p2 - p1) / abs(p1)
    return dict(
        gdot=avg("gdot", rows), p=avg("p", rows), sxy=avg("sxy", rows),
        syy=avg("syy", rows), tau=avg("tau", rows), T=avg("T", rows),
        phi=avg("phi", rows), drift=drift,
    )


def collect():
    """Read every case's steady average and form the enduring-contact residual."""
    out = []
    for phi_target in all_cases():
        case = case_name(phi_target)
        csv_path = os.path.join(DATA_DIR, case, "enduring_contact_results.csv")
        if not os.path.isfile(csv_path):
            print(f"  (missing {case}, skipping)")
            continue
        s = steady_average(csv_path)
        if s is None or s["p"] <= 0.0:
            print(f"  ({case}: no steady data, skipping)")
            continue
        p_dem = s["p"]
        p_kt = kt_pressure(s["phi"], s["T"], RESTITUTION)
        sigma_contact = p_dem - p_kt
        out.append(dict(
            phi_target=phi_target, phi=s["phi"], T=s["T"], gdot=s["gdot"],
            p_dem=p_dem, p_kt=p_kt, sigma_contact=sigma_contact,
            frac_contact=(sigma_contact / p_dem if p_dem > 0 else float("nan")),
            drift=s["drift"],
        ))
    out.sort(key=lambda d: d["phi"])
    return out


def validate(pts):
    """PASS/FAIL on the enduring-contact signature:
      1. all pressures positive (sane stress recorder);
      2. dilute floor: σ_contact ≈ 0 at the lowest Φ (KT explains it);
      3. growth: σ_contact at the densest Φ clearly exceeds the dilute floor.
    Steady-state drift is reported (warned), not failed, since the dense cases
    near jamming legitimately plateau slowly."""
    ok = True
    print("\n=== Enduring-contact residual σ_contact(Φ) = p_DEM − p_KT(Φ, T) ===")
    print(f"  {'Φ':>6} {'T':>11} {'p_DEM':>12} {'p_KT':>12} {'σ_contact':>12} "
          f"{'σ/p_DEM':>8} {'drift':>7}")
    for p in pts:
        print(f"  {p['phi']:6.3f} {p['T']:11.4e} {p['p_dem']:12.4e} {p['p_kt']:12.4e} "
              f"{p['sigma_contact']:12.4e} {p['frac_contact']:8.2f} "
              f"{100*p.get('drift', float('nan')):6.0f}%")

    if not pts:
        print("  no data"); return False

    if not all(p["p_dem"] > 0.0 for p in pts):
        print("  FAIL: non-positive p_DEM in some case"); ok = False
    else:
        print("  all p_DEM > 0  → PASS")

    lo, hi = pts[0], pts[-1]
    floor = abs(lo["frac_contact"])
    if floor < 0.20:
        print(f"  dilute floor: σ_contact/p_DEM = {lo['frac_contact']:.2f} at Φ={lo['phi']:.3f} (≈0)  → PASS")
    else:
        print(f"  dilute floor: σ_contact/p_DEM = {lo['frac_contact']:.2f} at Φ={lo['phi']:.3f} (not ≈0)  → FAIL")
        ok = False

    if hi["sigma_contact"] > lo["sigma_contact"] and hi["frac_contact"] > 0.20:
        print(f"  growth: σ_contact/p_DEM = {hi['frac_contact']:.2f} at Φ={hi['phi']:.3f} (branch opened)  → PASS")
    else:
        print(f"  growth: σ_contact/p_DEM = {hi['frac_contact']:.2f} at Φ={hi['phi']:.3f} (no clear branch)  → FAIL")
        ok = False

    not_steady = [p for p in pts if not (p.get("drift", 1.0) < 0.20)]
    if not_steady:
        print(f"  ⚠ {len(not_steady)}/{len(pts)} cases drift > 20% — raise TARGET_STRAIN; "
              f"see plots/convergence.png (warning, not a failure)")
    return ok


def write_sigma_csv(pts):
    os.makedirs(DATA_DIR, exist_ok=True)
    with open(SIGMA_CSV, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["phi", "T", "p_dem", "p_kt", "sigma_contact", "frac_contact"])
        for p in pts:
            w.writerow([f"{p['phi']:.5f}", f"{p['T']:.6e}", f"{p['p_dem']:.6e}",
                        f"{p['p_kt']:.6e}", f"{p['sigma_contact']:.6e}",
                        f"{p['frac_contact']:.5f}"])
    print(f"  wrote {SIGMA_CSV}")


def graph():
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib not available; skipping plots")
        plt = None

    os.makedirs(PLOT_DIR, exist_ok=True)
    pts = collect()
    if not pts:
        print("no data collected — run `start` first")
        sys.exit(1)

    passed = validate(pts)
    write_sigma_csv(pts)

    if plt is not None:
        phis = [p["phi"] for p in pts]

        # ── σ_contact(Φ): the deliverable ──
        fig, ax = plt.subplots(figsize=(6.2, 4.4))
        ax.axhline(0.0, color="grey", lw=0.8)
        ax.plot(phis, [p["sigma_contact"] for p in pts], "o-", c="tab:red",
                label=r"$\sigma_\mathrm{contact}=p_\mathrm{DEM}-p_\mathrm{KT}$")
        ax.set_xlabel("Φ"); ax.set_ylabel("enduring-contact stress  σ_contact [Pa]")
        ax.set_title("Enduring-contact (rate-independent) stress branch")
        ax.legend(); ax.grid(True, alpha=0.3)
        fig.tight_layout(); fig.savefig(os.path.join(PLOT_DIR, "sigma_contact.png"), dpi=130)
        plt.close(fig)

        # ── Stress decomposition: p_DEM vs collisional p_KT vs residual ──
        fig, ax = plt.subplots(figsize=(6.2, 4.4))
        ax.plot(phis, [p["p_dem"] for p in pts], "s-", c="tab:blue", label=r"$p_\mathrm{DEM}$ (measured)")
        ax.plot(phis, [p["p_kt"] for p in pts], "^--", c="tab:green", label=r"$p_\mathrm{KT}(\Phi,T)$ (Lun, collisional)")
        ax.plot(phis, [p["sigma_contact"] for p in pts], "o-", c="tab:red", label=r"$\sigma_\mathrm{contact}$ (residual)")
        ax.set_xlabel("Φ"); ax.set_ylabel("pressure [Pa]")
        ax.set_title("Stress decomposition: DEM = collisional KT + enduring contact")
        ax.legend(); ax.grid(True, alpha=0.3)
        fig.tight_layout(); fig.savefig(os.path.join(PLOT_DIR, "stress_decomposition.png"), dpi=130)
        plt.close(fig)

        # ── Convergence diagnostic: p vs strain per case ──
        fig, ax = plt.subplots(figsize=(6.4, 4.4))
        smax = 0.0
        for phi_t in PHI_GRID:
            cp = os.path.join(DATA_DIR, case_name(phi_t), "enduring_contact_results.csv")
            if not os.path.isfile(cp):
                continue
            series = read_shear_series(cp)
            if not series or not series["strain"]:
                continue
            ax.plot(series["strain"], series["p"], lw=1, label=f"Φ≈{phi_t:.2f}")
            smax = max(smax, max(series["strain"]))
        if smax > 0:
            ax.axvspan(smax * 0.5, smax, color="grey", alpha=0.15, label="averaging window")
            ax.set_xlabel("strain γ = γ̇·t"); ax.set_ylabel("p [Pa]")
            ax.set_title("Convergence to steady state"); ax.grid(True, alpha=0.3)
            ax.legend(fontsize=7, ncol=2)
            fig.tight_layout(); fig.savefig(os.path.join(PLOT_DIR, "convergence.png"), dpi=130)
        plt.close(fig)

        print(f"\nplots written to {PLOT_DIR}")

    if not passed:
        sys.exit(1)


def main():
    cmd = sys.argv[1] if len(sys.argv) > 1 else "all"
    if cmd == "generate":
        generate()
    elif cmd == "start":
        start()
    elif cmd == "graph":
        graph()
    elif cmd == "all":
        generate(); start(); graph()
    else:
        print(__doc__); sys.exit(1)


if __name__ == "__main__":
    main()
