#!/usr/bin/env python3
"""
SPH glass-sphere calibration · 01 — Lees–Edwards simple-shear rheometer (μ(I)).

A triperiodic box of glass beads (gravity off) is sheared at constant rate γ̇ via
the native Lees–Edwards triclinic deform style. Each run is held at fixed volume
(fixed Φ) while γ̇ is swept; in steady state the recorder reports the stress
tensor, granular temperature T, and Φ. From these we form the inertial number
I = γ̇·d·√(ρ_s/P), the friction μ = |σ_xy|/P, and Φ(I), and fit the μ(I) law that
the MUD SPH solver consumes — together with ρ_c = Φ_max·ρ_s.

This is the FRICTIONAL/production rheometer (canonical glass μ_p = 0.16). The
frictionless kinetic-theory cross-check lives in examples/bench_lebc_shear.

Commands (from anywhere):
    python3 examples/SPH_glass_sphere_calibration/01_shear_rheology/sweep.py generate
    python3 examples/SPH_glass_sphere_calibration/01_shear_rheology/sweep.py start
    python3 examples/SPH_glass_sphere_calibration/01_shear_rheology/sweep.py graph
    python3 examples/SPH_glass_sphere_calibration/01_shear_rheology/sweep.py   # all three

Outputs:
    sweep/<case>/config.toml                         per-case configs   (gitignored)
    data/<case>/sphcal_shear_rheology_results.csv    per-case series    (gitignored)
    data/calibration.yaml                            μ(I)/Φ(I) fit → MUD(gitignored)
    plots/mu_of_I.png, phi_of_I.png, convergence.png                    (tracked)

References: GDR MiDi 2004; da Cruz et al. 2005 (I-scaling).
"""

import os
import sys
import csv
import math
import subprocess

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", "..", ".."))
EXAMPLE = "sphcal_shear_rheology"

DATA_DIR = os.path.join(SCRIPT_DIR, "data")
SWEEP_DIR = os.path.join(SCRIPT_DIR, "sweep")
PLOT_DIR = os.path.join(SCRIPT_DIR, "plots")

# ── Physics (shared with config.toml) ────────────────────────────────────────
L_FINAL = 0.006           # target (sheared) cubic box side [m]
PHI_LOOSE = 0.30          # insertion density (random insertion saturates ≈0.38)
RMIN, RMAX = 0.000225, 0.000275   # uniform radius [m] → d ≈ 0.5 mm
DENSITY = 2500.0          # kg/m^3 (ρ_s)
YOUNGS_MOD = 7.0e7         # softened from ~65 GPa real glass (rigid-grain limit)
POISSON = 0.245            # glass
RESTITUTION = 0.926        # measured glass–glass COR (canonical glass-bead material)
FRICTION = 0.16            # measured glass–glass sliding μ_p (frictional production)
ROLLING = 0.10             # measured glass-bead rolling friction μ_r (default "constant" model)
DT = 2.0e-7
SETTLE_STEPS = 20_000
COMPRESS_STEPS = 60_000   # quasi-static compaction loose → target Φ
# Shear duration is set by total STRAIN, not a fixed step count: strain = γ̇·dt·steps,
# so a fixed step count gives almost no strain at low γ̇. Steady state needs strain ≫ 1
# (also to dissipate the compression heat), so steps = TARGET_STRAIN/(γ̇·dt).
TARGET_STRAIN = 30.0
MIN_SHEAR_STEPS = 40_000
THERMO = 2000

D_MEAN = RMIN + RMAX                       # mean diameter (= 2·mean radius) [m]
R3_MEAN = (RMAX**4 - RMIN**4) / (4.0 * (RMAX - RMIN))   # <r³> for uniform radius
V_PARTICLE = (4.0 / 3.0) * math.pi * R3_MEAN            # mean particle volume

# ── Sweep grid ───────────────────────────────────────────────────────────────
# Target Φ reached by compressing a loose insert; γ̇ swept per Φ to span I.
# A grid over (Φ, γ̇) populates the μ(I)/Φ(I) curve from quasi-static to inertial.
PHI_GRID = [0.40, 0.50, 0.55, 0.58, 0.60]
GDOT_GRID = [10.0, 30.0, 100.0, 300.0]


def count_for_phi(phi):
    """Particle count to reach target Φ in the final (sheared) box."""
    return max(1, round(phi * L_FINAL**3 / V_PARTICLE))


def loose_box(count):
    """Initial box side so `count` particles sit at PHI_LOOSE before compression."""
    return (count * V_PARTICLE / PHI_LOOSE) ** (1.0 / 3.0)


def case_name(phi, gdot):
    return f"phi{phi:.2f}_g{gdot:g}"


def all_cases():
    for phi in PHI_GRID:
        for gdot in GDOT_GRID:
            yield phi, gdot


# ── config.toml template ─────────────────────────────────────────────────────
CONFIG_TEMPLATE = """\
# Auto-generated by sweep.py — Lees–Edwards shear, case {case}.
# Stages: settle (loose) → compress (loose box L_init → target box L_final, i.e.
# Φ_loose → Φ_target) → shear (Lees–Edwards xy at fixed target volume).
[comm]
processors_x = 1
processors_y = 1
processors_z = 1

[domain]
x_low = 0.0
x_high = {l_init}
y_low = 0.0
y_high = {l_init}
z_low = 0.0
z_high = {l_init}
boundary_x = "periodic"
boundary_y = "periodic"
boundary_z = "periodic"

[neighbor]
skin_fraction = 1.2
bin_size = {bin_size}
every = 1

[gravity]
gx = 0.0
gy = 0.0
gz = 0.0

[dem]
contact_model = "hertz"

[[dem.materials]]
name = "glass"
youngs_mod = {E}
poisson_ratio = {nu}
restitution = {e}
friction = {mu_p}
rolling_friction = {mu_r}

[[particles.insert]]
material = "glass"
count = {count}
radius = {{ distribution = "uniform", min = {rmin}, max = {rmax} }}
density = {density}
velocity = 0.02
region = {{ type = "block", min = [0.0, 0.0, 0.0], max = [{l_init}, {l_init}, {l_init}] }}
seed = 12345

[output]
dir = "{out_dir}"

[[run]]
name = "settle"
steps = {settle}
thermo = {thermo}
dt = {dt}

# Compress the loose pack down to the target box (→ target Φ), atoms remapped
# affinely. Velocity-style ramp reaches L_final deterministically at stage end:
# each box length goes L_init → L_final at v = (L_final − L_init)/(dt·steps).
[[run]]
name = "compress"
steps = {compress}
thermo = {thermo}
dt = {dt}
deform = {{ x = {{ style = "vel", velocity = {compress_vel} }}, y = {{ style = "vel", velocity = {compress_vel} }}, z = {{ style = "vel", velocity = {compress_vel} }} }}

# Lees–Edwards simple shear at fixed target volume.
[[run]]
name = "shear"
steps = {shear}
thermo = {thermo}
dt = {dt}
deform = {{ xy = {{ style = "erate", rate = {gdot} }} }}
"""


def generate():
    os.makedirs(SWEEP_DIR, exist_ok=True)
    n = 0
    for phi, gdot in all_cases():
        case = case_name(phi, gdot)
        cdir = os.path.join(SWEEP_DIR, case)
        os.makedirs(cdir, exist_ok=True)
        out_dir = os.path.join(DATA_DIR, case)
        count = count_for_phi(phi)
        l_init = loose_box(count)
        # Deterministic ramp L_init → L_final over the compress stage (sign handles
        # both compaction, target Φ > Φ_loose, and dilation, target Φ < Φ_loose).
        compress_vel = (L_FINAL - l_init) / (DT * COMPRESS_STEPS)
        # Strain-based shear duration: reach TARGET_STRAIN regardless of γ̇.
        shear_steps = max(MIN_SHEAR_STEPS, round(TARGET_STRAIN / (gdot * DT)))
        cfg = CONFIG_TEMPLATE.format(
            case=case, l_init=l_init, l_final=L_FINAL, bin_size=1.2 * D_MEAN,
            E=YOUNGS_MOD, nu=POISSON, e=RESTITUTION, mu_p=FRICTION, mu_r=ROLLING, count=count,
            rmin=RMIN, rmax=RMAX, density=DENSITY, out_dir=out_dir,
            settle=SETTLE_STEPS, compress=COMPRESS_STEPS, shear=shear_steps,
            thermo=THERMO, dt=DT, gdot=gdot, compress_vel=compress_vel,
        )
        with open(os.path.join(cdir, "config.toml"), "w") as f:
            f.write(cfg)
        n += 1
    print(f"generated {n} case configs under {SWEEP_DIR}")


def build():
    print("building example (release)...")
    subprocess.run(
        ["cargo", "build", "--release", "--no-default-features", "--example", EXAMPLE],
        cwd=REPO_ROOT, check=True,
    )


def start():
    if not os.path.isdir(SWEEP_DIR):
        generate()
    build()
    exe = os.path.join(REPO_ROOT, "target", "release", "examples", EXAMPLE)
    for phi, gdot in all_cases():
        case = case_name(phi, gdot)
        cfg = os.path.join(SWEEP_DIR, case, "config.toml")
        log = os.path.join(SWEEP_DIR, case, "run.log")
        print(f"running {case} ...")
        with open(log, "w") as lf:
            subprocess.run([exe, cfg], cwd=REPO_ROOT, stdout=lf, stderr=subprocess.STDOUT, check=True)
    print("all runs complete")


# ── Analysis ─────────────────────────────────────────────────────────────────
def read_shear_series(csv_path):
    """Read the shear-stage time series (gdot>0): strain (since shear start) and the
    Bagnold-normalized stresses + T*, for the convergence-to-steady-state diagnostic."""
    rows = [r for r in csv.DictReader(open(csv_path)) if float(r["gdot"]) > 0.0]
    if not rows:
        return None
    t0 = float(rows[0]["time"])
    out = dict(strain=[], p_bag=[], s_bag=[], Tstar=[])
    for r in rows:
        g = float(r["gdot"]); t = float(r["time"])
        bag = DENSITY * D_MEAN**2 * g * g
        out["strain"].append(g * (t - t0))
        out["p_bag"].append(float(r["p"]) / bag)
        out["s_bag"].append(abs(float(r["sxy"])) / bag)
        out["Tstar"].append(float(r["T"]) / (g * D_MEAN) ** 2)
    return out


def steady_average(csv_path, frac=0.5):
    """Average the steady-shear window: sheared rows (gdot>0) past `frac` of them.
    Also returns a `drift` = relative change of p between the two halves of that
    window — a steadiness indicator (small ⇒ plateaued)."""
    rows = [r for r in csv.DictReader(open(csv_path)) if float(r["gdot"]) > 0.0]
    if not rows:
        return None
    rows = rows[int(len(rows) * frac):]
    def avg(key, rs):
        return sum(float(r[key]) for r in rs) / len(rs)
    half = len(rows) // 2
    drift = float("nan")
    if half >= 1:
        p1, p2 = avg("p", rows[:half]), avg("p", rows[half:])
        if p1 != 0:
            drift = abs(p2 - p1) / abs(p1)
    return dict(
        gdot=avg("gdot", rows), p=avg("p", rows), sxy=avg("sxy", rows),
        syy=avg("syy", rows), tau=avg("tau", rows), T=avg("T", rows),
        phi=avg("phi", rows), drift=drift,
    )


def collect():
    """Read every case's steady average into a list of dicts."""
    out = []
    for phi_target, gdot in all_cases():
        case = case_name(phi_target, gdot)
        csv_path = os.path.join(DATA_DIR, case, "sphcal_shear_rheology_results.csv")
        if not os.path.isfile(csv_path):
            print(f"  (missing {case}, skipping)")
            continue
        s = steady_average(csv_path)
        if s is None or s["p"] <= 0.0:
            print(f"  ({case}: no steady data, skipping)")
            continue
        I = s["gdot"] * D_MEAN * math.sqrt(DENSITY / s["p"])
        mu = abs(s["sxy"]) / s["p"]
        out.append(dict(phi_target=phi_target, I=I, mu=mu, **s))
    return out


def fit_mu_of_I(points):
    """Least-squares fit μ(I) = μ_s + (μ2 − μ_s)/(I0/I + 1) via coarse grid search."""
    best = None
    for mu_s in [x / 100 for x in range(5, 50)]:
        for mu2 in [x / 100 for x in range(int(mu_s * 100), 120)]:
            for I0 in [0.05 * k for k in range(1, 21)]:
                err = 0.0
                for p in points:
                    pred = mu_s + (mu2 - mu_s) / (I0 / p["I"] + 1.0)
                    err += (pred - p["mu"]) ** 2
                if best is None or err < best[0]:
                    best = (err, mu_s, mu2, I0)
    return best[1], best[2], best[3]


def validate(points):
    """Print the μ(I)/Φ(I) fit and steady-state diagnostics; return PASS/FAIL bool.

    PASS requires: (1) every case sane — p>0, finite σ_xy, 0<Φ<1; (2) the fitted
    closure ordered physically μ_s < μ_2 with 0 < I_0; (3) most cases steady
    (drift < 15%). The fitted (μ_s, μ_2, I_0, Φ_max, ρ_c) are written to
    data/calibration.yaml for mud_constitutive::MaterialParams."""
    ok = True

    # ── sanity of every measured point ──
    print("\n=== Steady shear measurements (frictional production) ===")
    print(f"  {'Φ_t':>5} {'γ̇':>6} {'Φ':>6} {'p':>11} {'σ_xy':>11} {'I':>8} {'μ':>7} {'drift':>6}")
    for p in sorted(points, key=lambda d: (d["phi_target"], d["gdot"])):
        sane = p["p"] > 0.0 and math.isfinite(p["sxy"]) and 0.0 < p["phi"] < 1.0
        ok = ok and sane
        print(f"  {p['phi_target']:5.2f} {p['gdot']:6.0f} {p['phi']:6.3f} "
              f"{p['p']:11.3e} {p['sxy']:11.3e} {p['I']:8.4f} {p['mu']:7.3f} "
              f"{100*p.get('drift', float('nan')):5.0f}%")

    # ── steadiness ──
    not_steady = [p for p in points if not (p.get("drift", 1.0) < 0.15)]
    if not_steady:
        print(f"  ⚠ {len(not_steady)}/{len(points)} cases not steady (drift ≥ 15%) — "
              f"raise TARGET_STRAIN; see plots/convergence.png")
    else:
        print(f"  all {len(points)} cases steady (drift < 15%)")

    # ── Bagnold scaling (σ ∝ γ̇²) per Φ — inertial-regime consistency ──
    print("\n=== Bagnold scaling (σ ∝ γ̇²) — per Φ ===")
    for phi_t in sorted(set(p["phi_target"] for p in points)):
        grp = sorted([p for p in points if p["phi_target"] == phi_t], key=lambda d: d["gdot"])
        if len(grp) < 2:
            continue
        ratios = [p["p"] / p["gdot"] ** 2 for p in grp]
        spread = (max(ratios) - min(ratios)) / (sum(ratios) / len(ratios))
        print(f"  Φ≈{phi_t:.2f}: p/γ̇² spread = {spread*100:.0f}% "
              f"({'Bagnold-like' if spread < 0.5 else 'rate-dependent (μ(I) regime)'})")

    return ok, not_steady


def write_calibration(mu_s, mu2, I0, phi_max, rho_c):
    os.makedirs(DATA_DIR, exist_ok=True)
    path = os.path.join(DATA_DIR, "calibration.yaml")
    with open(path, "w") as f:
        f.write("# DEM-calibrated μ(I) closure for mud_constitutive::MaterialParams\n")
        f.write("material: glass_beads_dem\n")
        f.write(f"rho_s: {DENSITY}\n")
        f.write(f"d: {D_MEAN}\n")
        f.write(f"mu_s: {mu_s:.4f}\n")
        f.write(f"mu_2: {mu2:.4f}\n")
        f.write(f"I_0: {I0:.4f}\n")
        f.write(f"phi_max: {phi_max:.4f}\n")
        f.write(f"rho_c: {rho_c:.2f}\n")
    print(f"  wrote {path}")


def graph():
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib not available; skipping plots")
        plt = None

    os.makedirs(PLOT_DIR, exist_ok=True)
    pts = collect()
    if not pts:
        print("no data collected — run `start` first")
        sys.exit(1)

    ok, _ = validate(pts)

    mu_s = mu2 = I0 = phi_max = rho_c = None
    if len(pts) >= 4:
        mu_s, mu2, I0 = fit_mu_of_I(pts)
        phi_max = max(p["phi"] for p in pts)
        rho_c = phi_max * DENSITY
        print("\n=== μ(I) / Φ(I) fit (frictional production sweep) ===")
        print(f"  μ_s = {mu_s:.3f}   μ_2 = {mu2:.3f}   I_0 = {I0:.3f}")
        print(f"  Φ_max = {phi_max:.3f}   ρ_c = Φ_max·ρ_s = {rho_c:.1f} kg/m³")
        # physical ordering of the fitted closure
        ok = ok and (mu_s < mu2) and (I0 > 0.0)
        write_calibration(mu_s, mu2, I0, phi_max, rho_c)
    else:
        ok = False
        print("\n(need ≥4 production points for a μ(I) fit)")

    if plt is not None:
        # μ(I)
        fig, ax = plt.subplots(figsize=(6, 4.2))
        ax.scatter([p["I"] for p in pts], [p["mu"] for p in pts], c="tab:blue", label="DEM (frictional)")
        if mu_s is not None:
            xs = [10 ** (-4 + 0.05 * k) for k in range(80)]
            ax.plot(xs, [mu_s + (mu2 - mu_s) / (I0 / x + 1.0) for x in xs], "k-",
                    label=f"fit: μ_s={mu_s:.2f}, μ_2={mu2:.2f}, I_0={I0:.2f}")
        ax.set_xscale("log"); ax.set_xlabel("inertial number I"); ax.set_ylabel("μ = |σ_xy| / P")
        ax.set_title("Lees–Edwards rheometer: μ(I)"); ax.legend(); ax.grid(True, alpha=0.3)
        fig.tight_layout(); fig.savefig(os.path.join(PLOT_DIR, "mu_of_I.png"), dpi=130); plt.close(fig)

        # Φ(I)
        fig, ax = plt.subplots(figsize=(6, 4.2))
        ax.scatter([p["I"] for p in pts], [p["phi"] for p in pts], c="tab:green")
        if phi_max is not None:
            ax.axhline(phi_max, ls="--", c="grey", label=f"Φ_max = {phi_max:.3f}")
            ax.legend()
        ax.set_xscale("log"); ax.set_xlabel("inertial number I"); ax.set_ylabel("Φ")
        ax.set_title("Lees–Edwards rheometer: Φ(I)"); ax.grid(True, alpha=0.3)
        fig.tight_layout(); fig.savefig(os.path.join(PLOT_DIR, "phi_of_I.png"), dpi=130); plt.close(fig)

        # Convergence diagnostic: σ_xy & T vs strain (confirms steady state).
        fig, (axp, axT) = plt.subplots(1, 2, figsize=(11, 4.4))
        plotted = 0
        smax = 0.0
        for phi_t, gdot in all_cases():
            path = os.path.join(DATA_DIR, case_name(phi_t, gdot), "sphcal_shear_rheology_results.csv")
            if not os.path.isfile(path):
                continue
            series = read_shear_series(path)
            if not series or not series["strain"]:
                continue
            lbl = f"Φ≈{phi_t:.2f}, γ̇={gdot:g}"
            axp.plot(series["strain"], series["s_bag"], lw=1, label=lbl)
            axT.plot(series["strain"], series["Tstar"], lw=1, label=lbl)
            smax = max(smax, max(series["strain"]))
            plotted += 1
        if plotted:
            for ax, ylab, title in ((axp, r"$\sigma_{xy}/\rho_s d^2\dot\gamma^2$", "Shear stress vs strain"),
                                    (axT, r"$T/(\dot\gamma d)^2$", "Granular temperature vs strain")):
                ax.axvspan(smax * 0.5, smax, color="grey", alpha=0.15, label="averaging window")
                ax.set_xlabel("strain γ = γ̇·t"); ax.set_ylabel(ylab); ax.set_yscale("log")
                ax.set_title(title); ax.grid(True, alpha=0.3)
            axp.legend(fontsize=7, ncol=2)
            fig.suptitle("Convergence to steady state (frictional production)")
            fig.tight_layout(); fig.savefig(os.path.join(PLOT_DIR, "convergence.png"), dpi=130)
        plt.close(fig)
        print(f"\nplots written to {PLOT_DIR}")

    print(f"\n{'PASS' if ok else 'FAIL'}")
    if not ok:
        sys.exit(1)


def main():
    cmd = sys.argv[1] if len(sys.argv) > 1 else "all"
    if cmd == "generate":
        generate()
    elif cmd == "start":
        start()
    elif cmd == "graph":
        graph()
    elif cmd == "all":
        generate(); start(); graph()
    else:
        print(__doc__); sys.exit(1)


if __name__ == "__main__":
    main()
